/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 female.glb -b -T --shadows 
Files: female.glb [8.9MB] > /Users/eax./Documents/practice/character/female/female-transformed.glb [719.75KB] (92%)
Author: Tatenashi (https://sketchfab.com/Tatenashi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/galaxia-anime-girl-485f95459fa747fdbe42c87203e1a156
Title: Galaxia anime girl
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

import { angleToRadians } from "@/utils/angleToRadians";

export default function Model(props) {
  const { scene } = useGLTF("/models/character/female/female-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root_030} rotation={[-1.563, 0, 3.141]}>
          <primitive
            object={nodes.J_Bip_C_Hips_031}
            position={[0, 0.838, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <primitive
              object={nodes.J_Bip_C_Spine_032}
              position={[0, -0.05, 0.009]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <primitive
                object={nodes.J_Bip_C_Chest_033}
                position={[0, 0.111, 0]}
                rotation={[0.226, 0, 0]}
              >
                <primitive
                  object={nodes.J_Bip_C_UpperChest_034}
                  position={[0, 0.117, 0]}
                  rotation={[-0.236, 0, 0]}
                >
                  <primitive
                    object={nodes.J_Sec_L_Bust1_035}
                    position={[-0.05, -0.018, -0.058]}
                    rotation={[-1.35, 0.022, 0.465]}
                  >
                    <primitive
                      object={nodes.J_Sec_L_Bust2_036}
                      position={[0, 0.054, 0]}
                    />
                  </primitive>
                  <primitive
                    object={nodes.J_Sec_R_Bust1_037}
                    position={[0.05, -0.018, -0.058]}
                    rotation={[-1.349, -0.023, -0.465]}
                  >
                    <primitive
                      object={nodes.J_Sec_R_Bust2_038}
                      position={[0, 0.054, 0]}
                    />
                  </primitive>
                  <primitive
                    object={nodes.J_Bip_C_Neck_039}
                    position={[0, 0.102, 0.045]}
                    rotation={[-0.002, 0, 0]}
                  >
                    <primitive
                      object={nodes.J_Bip_C_Head_040}
                      position={[0, 0.067, 0]}
                      rotation={[-0.161, -0.007, -0.01]}
                    >
                      <primitive
                        object={nodes.J_Adj_L_FaceEye_041}
                        position={[-0.021, 0.066, -0.009]}
                      />
                      <primitive
                        object={nodes.J_Adj_R_FaceEye_042}
                        position={[0.019, 0.066, -0.009]}
                      />
                      <primitive
                        object={
                          nodes[
                            "HairJoint-48bc483b-985c-4d46-9d73-f431333dc8fc_043"
                          ]
                        }
                        position={[-0.008, 0.165, -0.042]}
                        rotation={[-2.634, -0.157, 0.176]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-1e034aff-cc61-492f-b094-f61103893332_044"
                            ]
                          }
                          position={[0, 0.082, 0]}
                        />
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-946f1f28-eb98-4f8c-a8d8-d62f505ec49c_045"
                          ]
                        }
                        position={[0.077, 0.109, -0.033]}
                        rotation={[-2.739, -0.089, 0.081]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-3c63832d-db3e-4311-81d0-63bae6430e26_046"
                            ]
                          }
                          position={[0, 0.07, 0]}
                        />
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-870f7b0d-645d-4866-b800-02bd383d441a_047"
                          ]
                        }
                        position={[0.056, 0.163, -0.023]}
                        rotation={[-2.724, 0.061, -0.088]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-52e54c7e-9465-4f61-a9e4-7e6e20a3753a_048"
                            ]
                          }
                          position={[0, 0.095, 0]}
                        />
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-6364c48d-738a-4392-9473-6b72c80ae1d3_049"
                          ]
                        }
                        position={[0.081, 0.085, -0.02]}
                        rotation={[-2.865, -0.174, 0.154]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-cbfa99f7-858d-440e-9a66-8440fb7d5f6c_050"
                            ]
                          }
                          position={[0, 0.075, 0]}
                        />
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-e11e4d6d-ac4a-4ec0-85d5-b35a869a7819_051"
                          ]
                        }
                        position={[-0.083, 0.08, -0.019]}
                        rotation={[-2.84, 0.213, -0.233]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-b3144768-62a3-4e52-9321-887830c92ad4_052"
                            ]
                          }
                          position={[0, 0.071, 0]}
                        />
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-1dd2efe1-1ce5-4913-9d0e-bff126ee36d6_053"
                          ]
                        }
                        position={[-0.08, 0.03, 0.041]}
                        rotation={[-2.905, 0.296, -0.298]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-3ffa3865-0536-44fe-a455-6f074f8972ed_054"
                            ]
                          }
                          position={[0, 0.054, 0]}
                        />
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-d864ab0d-a5b9-4009-99b5-15cc4439f31f_055"
                          ]
                        }
                        position={[0.016, 0.009, 0.098]}
                        rotation={[-2.661, -0.118, 0.124]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-76111e00-ce6f-4c9d-8ea0-f151e76183b9_056"
                            ]
                          }
                          position={[0, 0.055, 0]}
                        />
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-4a0d17a0-2228-4c74-b52b-8503ab071062_057"
                          ]
                        }
                        position={[-0.055, 0.149, -0.033]}
                        rotation={[-2.684, -0.2, 0.218]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-8851717e-8ec1-411b-867b-c2e52230e424_058"
                            ]
                          }
                          position={[0, 0.053, 0]}
                          rotation={[-0.138, 0.16, -0.131]}
                        >
                          <primitive
                            object={
                              nodes[
                                "HairJoint-7ab59d1b-7076-4b0a-8083-0d868be65dec_059"
                              ]
                            }
                            position={[0, 0.053, 0]}
                          />
                        </primitive>
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-fff12439-b4d7-42ad-9012-c5c1add7e744_060"
                          ]
                        }
                        position={[-0.05, 0.171, 0.024]}
                        rotation={[-2.477, -0.644, 0.891]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-7cadd42c-efb2-4205-9f2d-76a2a17c6075_061"
                            ]
                          }
                          position={[0, 0.07, 0]}
                          rotation={[0.276, 0.679, -0.882]}
                        >
                          <primitive
                            object={
                              nodes[
                                "HairJoint-164a7341-d7c5-4dca-a944-64d17e482469_062"
                              ]
                            }
                            position={[0, 0.074, 0]}
                          />
                        </primitive>
                      </primitive>
                      <primitive
                        object={
                          nodes[
                            "HairJoint-5752602b-7220-4e08-87de-d701aec08000_063"
                          ]
                        }
                        position={[0.048, 0.173, 0.024]}
                        rotation={[-2.503, 0.613, -0.868]}
                      >
                        <primitive
                          object={
                            nodes[
                              "HairJoint-21fb9f19-3d10-481d-9d81-aa958d3eecdb_064"
                            ]
                          }
                          position={[0, 0.069, 0]}
                          rotation={[0.268, -0.652, 0.848]}
                        >
                          <primitive
                            object={
                              nodes[
                                "HairJoint-eebbff2a-f3c9-42c1-95e0-2c7d058524c3_065"
                              ]
                            }
                            position={[0, 0.074, 0]}
                          />
                        </primitive>
                      </primitive>
                      <primitive
                        object={nodes.J_Bip_C_Head_collider_0_07}
                        position={[-0.001, 0.089, 0.039]}
                        rotation={[-1.282, -0.008, -3.131]}
                      />
                    </primitive>
                    <primitive
                      object={nodes.J_Bip_C_Neck_collider_0_06}
                      position={[0, 0.028, -0.012]}
                      rotation={[-1.443, -0.001, -3.141]}
                    />
                  </primitive>
                  <primitive
                    object={nodes.J_Bip_L_Shoulder_066}
                    position={[-0.021, 0.078, 0.036]}
                    rotation={[-1.616, -0.159, 1.481]}
                  >
                    <primitive
                      object={nodes.J_Bip_L_UpperArm_067}
                      position={[0, 0.08, 0]}
                      rotation={[angleToRadians(-50), -0.115, 0.073]}
                    >
                      <primitive
                        object={nodes.J_Bip_L_LowerArm_068}
                        position={[0, 0.197, 0]}
                        rotation={[0.045, -0.044, -0.072]}
                      >
                        <primitive
                          object={nodes.J_Bip_L_Hand_069}
                          position={[0, 0.191, 0]}
                          rotation={[0.078, -0.068, 0.06]}
                        >
                          <primitive
                            object={nodes.J_Bip_L_Index1_070}
                            position={[0.018, 0.056, 0]}
                            rotation={[-0.075, 0.074, -0.13]}
                          >
                            <primitive
                              object={nodes.J_Bip_L_Index2_071}
                              position={[0, 0.029, 0]}
                              rotation={[-0.031, 0.025, 0.044]}
                            >
                              <primitive
                                object={nodes.J_Bip_L_Index3_072}
                                position={[0, 0.018, 0]}
                                rotation={[-0.005, 0.004, 0.021]}
                              >
                                <primitive
                                  object={nodes.J_Bip_L_Index3_end_073}
                                  position={[0, 0.021, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_L_Little1_074}
                            position={[-0.025, 0.054, 0.001]}
                            rotation={[-0.081, 0.078, 0.029]}
                          >
                            <primitive
                              object={nodes.J_Bip_L_Little2_075}
                              position={[0, 0.027, 0]}
                              rotation={[0.049, -0.047, 0.055]}
                            >
                              <primitive
                                object={nodes.J_Bip_L_Little3_076}
                                position={[0, 0.016, 0]}
                                rotation={[0.019, -0.021, -0.026]}
                              >
                                <primitive
                                  object={nodes.J_Bip_L_Little3_end_077}
                                  position={[0, 0.017, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_L_Middle1_078}
                            position={[0.003, 0.058, 0.003]}
                            rotation={[-0.108, 0.106, -0.036]}
                          >
                            <primitive
                              object={nodes.J_Bip_L_Middle2_079}
                              position={[0, 0.032, 0]}
                              rotation={[-0.073, 0.066, 0.023]}
                            >
                              <primitive
                                object={nodes.J_Bip_L_Middle3_080}
                                position={[0, 0.02, 0]}
                                rotation={[0.041, -0.04, 0.011]}
                              >
                                <primitive
                                  object={nodes.J_Bip_L_Middle3_end_081}
                                  position={[0, 0.022, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_L_Ring1_082}
                            position={[-0.011, 0.058, 0.004]}
                            rotation={[-0.088, 0.085, 0.025]}
                          >
                            <primitive
                              object={nodes.J_Bip_L_Ring2_083}
                              position={[0, 0.03, 0]}
                              rotation={[0.052, -0.052, -0.007]}
                            >
                              <primitive
                                object={nodes.J_Bip_L_Ring3_084}
                                position={[0, 0.017, 0]}
                                rotation={[-0.02, 0.02, 0.02]}
                              >
                                <primitive
                                  object={nodes.J_Bip_L_Ring3_end_085}
                                  position={[0, 0.018, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_L_Thumb1_086}
                            position={[0.015, 0.002, -0.007]}
                            rotation={[-0.095, 0.128, -0.786]}
                          >
                            <primitive
                              object={nodes.J_Bip_L_Thumb2_087}
                              position={[0, 0.041, 0]}
                              rotation={[0.003, -0.004, 0.074]}
                            >
                              <primitive
                                object={nodes.J_Bip_L_Thumb3_088}
                                position={[0, 0.025, 0]}
                                rotation={[0.017, -0.006, -0.077]}
                              >
                                <primitive
                                  object={nodes.J_Bip_L_Thumb3_end_089}
                                  position={[0, 0.019, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_L_Hand_collider_0_015}
                            position={[0.001, 0.017, -0.001]}
                            rotation={[-0.071, 0.07, 1.598]}
                          />
                        </primitive>
                        <primitive
                          object={nodes.J_Bip_L_LowerArm_collider_0_011}
                          rotation={[0.003, -0.002, 1.653]}
                        />
                        <primitive
                          object={nodes.J_Bip_L_LowerArm_collider_1_012}
                          position={[0, 0.047, 0]}
                          rotation={[0.003, -0.002, 1.653]}
                        />
                        <primitive
                          object={nodes.J_Bip_L_LowerArm_collider_2_013}
                          position={[0, 0.094, 0]}
                          rotation={[0.003, -0.002, 1.653]}
                        />
                        <primitive
                          object={nodes.J_Bip_L_LowerArm_collider_3_014}
                          position={[0, 0.14, 0]}
                          rotation={[0.003, -0.002, 1.653]}
                        />
                      </primitive>
                      <primitive
                        object={nodes.J_Bip_L_UpperArm_collider_0_08}
                        position={[0, 0, -0.009]}
                        rotation={[0.047, -0.046, 1.581]}
                      />
                      <primitive
                        object={nodes.J_Bip_L_UpperArm_collider_1_09}
                        position={[0, 0.07, -0.009]}
                        rotation={[0.047, -0.046, 1.581]}
                      />
                      <primitive
                        object={nodes.J_Bip_L_UpperArm_collider_2_010}
                        position={[0, 0.14, -0.009]}
                        rotation={[0.047, -0.046, 1.581]}
                      />
                    </primitive>
                  </primitive>
                  <primitive
                    object={nodes.J_Bip_R_Shoulder_090}
                    position={[0.021, 0.078, 0.036]}
                    rotation={[-1.617, 0.156, -1.482]}
                  >
                    <primitive
                      object={nodes.J_Bip_R_UpperArm_091}
                      position={[0, 0.08, 0]}
                      rotation={[angleToRadians(-50), 0.115, -0.073]}
                    >
                      <primitive
                        object={nodes.J_Bip_R_LowerArm_092}
                        position={[0, 0.196, 0]}
                        rotation={[0.045, 0.044, 0.072]}
                      >
                        <primitive
                          object={nodes.J_Bip_R_Hand_093}
                          position={[0, 0.191, 0]}
                          rotation={[0.078, 0.067, -0.06]}
                        >
                          <primitive
                            object={nodes.J_Bip_R_Index1_094}
                            position={[-0.018, 0.056, 0]}
                            rotation={[-0.075, -0.073, 0.13]}
                          >
                            <primitive
                              object={nodes.J_Bip_R_Index2_095}
                              position={[0, 0.029, 0]}
                              rotation={[-0.031, -0.025, -0.044]}
                            >
                              <primitive
                                object={nodes.J_Bip_R_Index3_096}
                                position={[0, 0.018, 0]}
                                rotation={[-0.005, -0.004, -0.021]}
                              >
                                <primitive
                                  object={nodes.J_Bip_R_Index3_end_097}
                                  position={[0, 0.021, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_R_Little1_098}
                            position={[0.025, 0.054, 0.001]}
                            rotation={[-0.081, -0.079, -0.029]}
                          >
                            <primitive
                              object={nodes.J_Bip_R_Little2_099}
                              position={[0, 0.027, 0]}
                              rotation={[0.049, 0.047, -0.055]}
                            >
                              <primitive
                                object={nodes.J_Bip_R_Little3_0100}
                                position={[0, 0.016, 0]}
                                rotation={[0.019, 0.022, 0.026]}
                              >
                                <primitive
                                  object={nodes.J_Bip_R_Little3_end_0101}
                                  position={[0, 0.017, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_R_Middle1_0102}
                            position={[-0.003, 0.058, 0.003]}
                            rotation={[-0.108, -0.106, 0.036]}
                          >
                            <primitive
                              object={nodes.J_Bip_R_Middle2_0103}
                              position={[0, 0.032, 0]}
                              rotation={[-0.073, -0.066, -0.023]}
                            >
                              <primitive
                                object={nodes.J_Bip_R_Middle3_0104}
                                position={[0, 0.02, 0]}
                                rotation={[0.041, 0.04, -0.011]}
                              >
                                <primitive
                                  object={nodes.J_Bip_R_Middle3_end_0105}
                                  position={[0, 0.022, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_R_Ring1_0106}
                            position={[0.011, 0.058, 0.004]}
                            rotation={[-0.088, -0.085, -0.025]}
                          >
                            <primitive
                              object={nodes.J_Bip_R_Ring2_0107}
                              position={[0, 0.03, 0]}
                              rotation={[0.052, 0.052, 0.007]}
                            >
                              <primitive
                                object={nodes.J_Bip_R_Ring3_0108}
                                position={[0, 0.017, 0]}
                                rotation={[-0.02, -0.02, -0.02]}
                              >
                                <primitive
                                  object={nodes.J_Bip_R_Ring3_end_0109}
                                  position={[0, 0.018, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_R_Thumb1_0110}
                            position={[-0.015, 0.002, -0.007]}
                            rotation={[-0.097, -0.125, 0.786]}
                          >
                            <primitive
                              object={nodes.J_Bip_R_Thumb2_0111}
                              position={[0, 0.041, 0]}
                              rotation={[0.004, 0.004, -0.074]}
                            >
                              <primitive
                                object={nodes.J_Bip_R_Thumb3_00}
                                position={[0, 0.025, 0]}
                                rotation={[0.017, 0.006, 0.077]}
                              >
                                <primitive
                                  object={nodes.J_Bip_R_Thumb3_end_01}
                                  position={[0, 0.019, 0]}
                                />
                              </primitive>
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.J_Bip_R_Hand_collider_0_023}
                            position={[-0.001, 0.017, -0.001]}
                            rotation={[-0.072, -0.069, -1.598]}
                          />
                        </primitive>
                        <primitive
                          object={nodes.J_Bip_R_LowerArm_collider_0_019}
                          rotation={[0.001, 0.003, -1.653]}
                        />
                        <primitive
                          object={nodes.J_Bip_R_LowerArm_collider_1_020}
                          position={[0, 0.047, 0]}
                          rotation={[0.001, 0.003, -1.653]}
                        />
                        <primitive
                          object={nodes.J_Bip_R_LowerArm_collider_2_021}
                          position={[0, 0.094, 0]}
                          rotation={[0.001, 0.003, -1.653]}
                        />
                        <primitive
                          object={nodes.J_Bip_R_LowerArm_collider_3_022}
                          position={[0, 0.14, 0]}
                          rotation={[0.001, 0.003, -1.653]}
                        />
                      </primitive>
                      <primitive
                        object={nodes.J_Bip_R_UpperArm_collider_0_016}
                        position={[0, 0, -0.009]}
                        rotation={[0.046, 0.047, -1.581]}
                      />
                      <primitive
                        object={nodes.J_Bip_R_UpperArm_collider_1_017}
                        position={[0, 0.07, -0.009]}
                        rotation={[0.046, 0.047, -1.581]}
                      />
                      <primitive
                        object={nodes.J_Bip_R_UpperArm_collider_2_018}
                        position={[0, 0.14, -0.009]}
                        rotation={[0.046, 0.047, -1.581]}
                      />
                    </primitive>
                  </primitive>
                  <primitive
                    object={nodes.J_Bip_C_UpperChest_collider_0_03}
                    position={[0, 0.004, -0.009]}
                    rotation={[-1.444, -0.001, -3.141]}
                  />
                  <primitive
                    object={nodes.J_Bip_C_UpperChest_collider_1_04}
                    position={[-0.047, 0.052, 0.033]}
                    rotation={[-1.444, -0.001, -3.141]}
                  />
                  <primitive
                    object={nodes.J_Bip_C_UpperChest_collider_2_05}
                    position={[0.047, 0.052, 0.033]}
                    rotation={[-1.444, -0.001, -3.141]}
                  />
                </primitive>
              </primitive>
              <primitive
                object={nodes.J_Bip_C_Spine_collider_0_02}
                rotation={[-1.454, -0.001, -3.141]}
              />
            </primitive>
            <primitive
              object={nodes.J_Bip_L_UpperLeg_0112}
              position={[-0.072, 0.037, -0.004]}
              rotation={[-0.026, -0.315, -0.06]}
            >
              <primitive
                object={nodes.J_Sec_L_SkirtBack_0113}
                position={[-0.033, 0.036, -0.105]}
                rotation={[-0.147, 0.281, 0.122]}
              >
                <primitive
                  object={nodes.J_Sec_L_SkirtBack_end_0114}
                  position={[0, 0.079, 0]}
                />
              </primitive>
              <primitive
                object={nodes.J_Sec_L_SkirtFront_0115}
                position={[0.044, 0.049, 0.107]}
                rotation={[0.011, 0.282, 0.088]}
              >
                <primitive
                  object={nodes.J_Sec_L_SkirtFront_end_0116}
                  position={[0, 0.085, 0]}
                />
              </primitive>
              <primitive
                object={nodes.J_Sec_L_SkirtSide_0117}
                position={[-0.089, 0.035, 0.034]}
                rotation={[-0.026, 0.074, 0.294]}
              >
                <primitive
                  object={nodes.J_Sec_L_SkirtSide_end_0118}
                  position={[0, 0.088, 0]}
                />
              </primitive>
              <primitive
                object={nodes.J_Bip_L_LowerLeg_0119}
                position={[0, 0.329, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <primitive
                  object={nodes.J_Bip_L_Foot_0120}
                  position={[0, 0.379, 0]}
                  rotation={[1.116, 0.008, 0.05]}
                >
                  <primitive
                    object={nodes.J_Bip_L_ToeBase_0121}
                    position={[0, 0.117, 0]}
                    rotation={[0.462, -0.003, -0.006]}
                  >
                    <primitive
                      object={nodes.J_Bip_L_ToeBase_end_0122}
                      position={[0, 0.042, 0]}
                    />
                  </primitive>
                </primitive>
              </primitive>
              <primitive
                object={nodes.J_Bip_L_UpperLeg_collider_0_024}
                rotation={[1.6, 0.05, 2.825]}
              />
              <primitive
                object={nodes.J_Bip_L_UpperLeg_collider_1_025}
                position={[0, 0.12, 0]}
                rotation={[1.6, 0.05, 2.825]}
              />
              <primitive
                object={nodes.J_Bip_L_UpperLeg_collider_2_026}
                position={[0, 0.22, 0]}
                rotation={[1.6, 0.05, 2.825]}
              />
            </primitive>
            <primitive
              object={nodes.J_Bip_R_UpperLeg_0123}
              position={[0.072, 0.037, -0.004]}
              rotation={[-0.026, 0.314, 0.06]}
            >
              <primitive
                object={nodes.J_Sec_R_SkirtBack_0124}
                position={[0.033, 0.036, -0.105]}
                rotation={[-0.147, -0.28, -0.122]}
              >
                <primitive
                  object={nodes.J_Sec_R_SkirtBack_end_0125}
                  position={[0, 0.079, 0]}
                />
              </primitive>
              <primitive
                object={nodes.J_Sec_R_SkirtFront_0126}
                position={[-0.045, 0.049, 0.107]}
                rotation={[0.012, -0.284, -0.085]}
              >
                <primitive
                  object={nodes.J_Sec_R_SkirtFront_end_0127}
                  position={[0, 0.085, 0]}
                />
              </primitive>
              <primitive
                object={nodes.J_Sec_R_SkirtSide_0128}
                position={[0.089, 0.035, 0.034]}
                rotation={[-0.026, -0.073, -0.294]}
              >
                <primitive
                  object={nodes.J_Sec_R_SkirtSide_end_0129}
                  position={[0, 0.088, 0]}
                />
              </primitive>
              <primitive
                object={nodes.J_Bip_R_LowerLeg_0130}
                position={[0, 0.329, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <primitive
                  object={nodes.J_Bip_R_Foot_0131}
                  position={[0, 0.379, 0]}
                  rotation={[1.116, -0.006, -0.05]}
                >
                  <primitive
                    object={nodes.J_Bip_R_ToeBase_0132}
                    position={[0, 0.117, 0]}
                    rotation={[0.462, 0.004, 0.007]}
                  >
                    <primitive
                      object={nodes.J_Bip_R_ToeBase_end_0133}
                      position={[0, 0.042, 0]}
                    />
                  </primitive>
                </primitive>
              </primitive>
              <primitive
                object={nodes.J_Bip_R_UpperLeg_collider_0_027}
                rotation={[1.611, -0.048, -2.824]}
              />
              <primitive
                object={nodes.J_Bip_R_UpperLeg_collider_1_028}
                position={[0, 0.12, 0]}
                rotation={[1.611, -0.048, -2.824]}
              />
              <primitive
                object={nodes.J_Bip_R_UpperLeg_collider_2_029}
                position={[0, 0.22, 0]}
                rotation={[1.611, -0.048, -2.824]}
              />
            </primitive>
          </primitive>
        </primitive>
      </primitive>
      <skinnedMesh
        geometry={nodes.Object_141.geometry}
        material={materials.F00_000_00_FaceMouth_00_FACE}
        skeleton={nodes.Object_141.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_142.geometry}
        material={materials.F00_000_00_Face_00_SKIN}
        skeleton={nodes.Object_142.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_144.geometry}
        material={materials.F00_001_01_Body_00_SKIN}
        skeleton={nodes.Object_144.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_145.geometry}
        material={materials.F00_001_01_Tops_01_CLOTH}
        skeleton={nodes.Object_145.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_146.geometry}
        material={materials.F00_001_01_Bottoms_01_CLOTH}
        skeleton={nodes.Object_146.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_147.geometry}
        material={materials.F00_001_01_Accessory_Tie_01_CLOTH}
        skeleton={nodes.Object_147.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_148.geometry}
        material={materials.F00_001_01_Shoes_01_CLOTH}
        skeleton={nodes.Object_148.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_149.geometry}
        material={materials.F00_000_HairBack_00_HAIR}
        skeleton={nodes.Object_149.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_151.geometry}
        material={materials.F00_000_Hair_00_HAIR}
        skeleton={nodes.Object_151.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_153.geometry}
        material={materials.F00_000_00_EyeWhite_00_EYE}
        skeleton={nodes.Object_153.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_154.geometry}
        material={materials.F00_000_00_EyeIris_00_EYE}
        skeleton={nodes.Object_154.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <skinnedMesh
        geometry={nodes.Object_155.geometry}
        material={materials.F00_000_00_EyeExtra_01_EYE}
        skeleton={nodes.Object_155.skeleton}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/character/female/female-transformed.glb");
