/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 male.glb -b -T --shadows 
Files: male.glb [5.55MB] > /Users/eax./Documents/practice/character/male/male-transformed.glb [749.6KB] (86%)
Author: sherry_arian (https://sketchfab.com/sherry_arian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boy-sherry-arian-ee590dfec61f40f3b2c1ca33819257b0
Title: boy sherry arian
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Model(props) {
  const { scene } = useGLTF("/models/character/male/male-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint}>
        <primitive
          object={nodes.Hips_66}
          position={[0, 1.019, 0.01]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <primitive
            object={nodes.Spine_55}
            position={[0, 0.098, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <primitive
              object={nodes.Spine1_54}
              position={[0, 0.13, 0]}
              rotation={[-0.064, 0, 0]}
            >
              <primitive
                object={nodes.Spine2_53}
                position={[0, 0.122, 0]}
                rotation={[0.094, 0, 0]}
              >
                <primitive
                  object={nodes.Neck_4}
                  position={[0, 0.156, 0]}
                  rotation={[0.409, 0, 0]}
                >
                  <primitive
                    object={nodes.Head_3}
                    position={[0, 0.123, 0]}
                    rotation={[-0.327, 0, 0]}
                  >
                    <primitive
                      object={nodes.HeadTop_End_0}
                      position={[0, 0.226, 0.037]}
                      rotation={[-0.007, 0, 0]}
                    />
                    <primitive
                      object={nodes.LeftEye_1}
                      position={[0.034, 0.086, 0.078]}
                      rotation={[-0.007, 0, 0]}
                    />
                    <primitive
                      object={nodes.RightEye_2}
                      position={[-0.034, 0.086, 0.078]}
                      rotation={[-0.007, 0, 0]}
                    />
                  </primitive>
                </primitive>
                <primitive
                  object={nodes.LeftShoulder_28}
                  position={[0.047, 0.141, -0.006]}
                  rotation={[1.56, -0.04, -1.58]}
                >
                  <primitive
                    object={nodes.LeftArm_27}
                    position={[0, 0.119, 0]}
                    rotation={[0.998, 0.019, -0.144]}
                  >
                    <primitive
                      object={nodes.LeftForeArm_26}
                      position={[0, 0.285, 0]}
                      rotation={[-0.107, 0.023, 0.447]}
                    >
                      <primitive
                        object={nodes.LeftHand_25}
                        position={[0, 0.252, 0]}
                        rotation={[0.094, 0.076, -0.041]}
                      >
                        <primitive
                          object={nodes.LeftHandThumb1_8}
                          position={[-0.032, 0.026, 0.005]}
                          rotation={[0.316, 0.122, 0.849]}
                        >
                          <primitive
                            object={nodes.LeftHandThumb2_7}
                            position={[0, 0.041, 0]}
                            rotation={[0.061, -0.169, -0.502]}
                          >
                            <primitive
                              object={nodes.LeftHandThumb3_6}
                              position={[0, 0.03, 0]}
                              rotation={[0.015, -0.051, -0.169]}
                            >
                              <primitive
                                object={nodes.LeftHandThumb4_5}
                                position={[0, 0.035, 0]}
                                rotation={[0.027, 0.105, -0.015]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.LeftHandIndex1_12}
                          position={[-0.035, 0.097, -0.007]}
                          rotation={[0.189, -0.089, 0.152]}
                        >
                          <primitive
                            object={nodes.LeftHandIndex2_11}
                            position={[0, 0.045, 0]}
                            rotation={[0.19, -0.007, 0.052]}
                          >
                            <primitive
                              object={nodes.LeftHandIndex3_10}
                              position={[0, 0.028, 0]}
                              rotation={[0.167, -0.155, -0.03]}
                            >
                              <primitive
                                object={nodes.LeftHandIndex4_9}
                                position={[0, 0.034, 0]}
                                rotation={[0.091, 0.113, -0.019]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.LeftHandMiddle1_16}
                          position={[-0.009, 0.1, -0.003]}
                          rotation={[0.08, -0.134, 0.036]}
                        >
                          <primitive
                            object={nodes.LeftHandMiddle2_15}
                            position={[0, 0.046, 0]}
                            rotation={[0.256, -0.008, 0.088]}
                          >
                            <primitive
                              object={nodes.LeftHandMiddle3_14}
                              position={[0, 0.035, 0]}
                              rotation={[0.405, -0.062, -0.076]}
                            >
                              <primitive
                                object={nodes.LeftHandMiddle4_13}
                                position={[0, 0.035, 0]}
                                rotation={[0.048, 0.045, -0.004]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.LeftHandRing1_20}
                          position={[0.015, 0.096, 0.002]}
                          rotation={[0.122, -0.117, -0.109]}
                        >
                          <primitive
                            object={nodes.LeftHandRing2_19}
                            position={[0, 0.042, 0]}
                            rotation={[0.376, -0.015, 0.096]}
                          >
                            <primitive
                              object={nodes.LeftHandRing3_18}
                              position={[0, 0.036, 0]}
                              rotation={[0.078, -0.011, 0.004]}
                            >
                              <primitive
                                object={nodes.LeftHandRing4_17}
                                position={[0, 0.03, 0]}
                                rotation={[0.014, -0.013, 0.044]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.LeftHandPinky1_24}
                          position={[0.039, 0.09, 0.011]}
                          rotation={[0.176, -0.171, -0.299]}
                        >
                          <primitive
                            object={nodes.LeftHandPinky2_23}
                            position={[0, 0.028, 0]}
                            rotation={[0.287, -0.405, 0.182]}
                          >
                            <primitive
                              object={nodes.LeftHandPinky3_22}
                              position={[0, 0.022, 0]}
                              rotation={[0.246, -0.021, 0.027]}
                            >
                              <primitive
                                object={nodes.LeftHandPinky4_21}
                                position={[0, 0.026, 0]}
                                rotation={[0.283, 0.204, -0.054]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                    </primitive>
                  </primitive>
                </primitive>
                <primitive
                  object={nodes.RightShoulder_52}
                  position={[-0.047, 0.141, -0.006]}
                  rotation={[1.56, 0.04, 1.58]}
                >
                  <primitive
                    object={nodes.RightArm_51}
                    position={[0, 0.119, 0]}
                    rotation={[0.998, -0.019, 0.144]}
                  >
                    <primitive
                      object={nodes.RightForeArm_50}
                      position={[0, 0.285, 0]}
                      rotation={[-0.107, -0.023, -0.447]}
                    >
                      <primitive
                        object={nodes.RightHand_49}
                        position={[0, 0.252, 0]}
                        rotation={[0.094, -0.076, 0.041]}
                      >
                        <primitive
                          object={nodes.RightHandThumb1_32}
                          position={[0.032, 0.026, 0.005]}
                          rotation={[0.316, -0.122, -0.849]}
                        >
                          <primitive
                            object={nodes.RightHandThumb2_31}
                            position={[0, 0.041, 0]}
                            rotation={[0.061, 0.169, 0.502]}
                          >
                            <primitive
                              object={nodes.RightHandThumb3_30}
                              position={[0, 0.03, 0]}
                              rotation={[0.015, 0.051, 0.169]}
                            >
                              <primitive
                                object={nodes.RightHandThumb4_29}
                                position={[0, 0.035, 0]}
                                rotation={[0.027, -0.105, 0.015]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.RightHandIndex1_36}
                          position={[0.035, 0.097, -0.007]}
                          rotation={[0.189, 0.089, -0.152]}
                        >
                          <primitive
                            object={nodes.RightHandIndex2_35}
                            position={[0, 0.045, 0]}
                            rotation={[0.19, 0.007, -0.052]}
                          >
                            <primitive
                              object={nodes.RightHandIndex3_34}
                              position={[0, 0.028, 0]}
                              rotation={[0.167, 0.155, 0.03]}
                            >
                              <primitive
                                object={nodes.RightHandIndex4_33}
                                position={[0, 0.034, 0]}
                                rotation={[0.091, -0.113, 0.019]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.RightHandMiddle1_40}
                          position={[0.009, 0.1, -0.003]}
                          rotation={[0.08, 0.134, -0.036]}
                        >
                          <primitive
                            object={nodes.RightHandMiddle2_39}
                            position={[0, 0.046, 0]}
                            rotation={[0.256, 0.008, -0.088]}
                          >
                            <primitive
                              object={nodes.RightHandMiddle3_38}
                              position={[0, 0.035, 0]}
                              rotation={[0.405, 0.062, 0.076]}
                            >
                              <primitive
                                object={nodes.RightHandMiddle4_37}
                                position={[0, 0.035, 0]}
                                rotation={[0.048, -0.045, 0.004]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.RightHandRing1_44}
                          position={[-0.015, 0.096, 0.002]}
                          rotation={[0.122, 0.117, 0.109]}
                        >
                          <primitive
                            object={nodes.RightHandRing2_43}
                            position={[0, 0.042, 0]}
                            rotation={[0.376, 0.015, -0.096]}
                          >
                            <primitive
                              object={nodes.RightHandRing3_42}
                              position={[0, 0.036, 0]}
                              rotation={[0.078, 0.011, -0.004]}
                            >
                              <primitive
                                object={nodes.RightHandRing4_41}
                                position={[0, 0.03, 0]}
                                rotation={[0.014, 0.014, -0.044]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive
                          object={nodes.RightHandPinky1_48}
                          position={[-0.039, 0.09, 0.011]}
                          rotation={[0.176, 0.171, 0.299]}
                        >
                          <primitive
                            object={nodes.RightHandPinky2_47}
                            position={[0, 0.028, 0]}
                            rotation={[0.287, 0.405, -0.182]}
                          >
                            <primitive
                              object={nodes.RightHandPinky3_46}
                              position={[0, 0.022, 0]}
                              rotation={[0.246, 0.021, -0.027]}
                            >
                              <primitive
                                object={nodes.RightHandPinky4_45}
                                position={[0, 0.026, 0]}
                                rotation={[0.283, -0.204, 0.054]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                    </primitive>
                  </primitive>
                </primitive>
              </primitive>
            </primitive>
          </primitive>
          <primitive
            object={nodes.LeftUpLeg_60}
            position={[0.095, 0.005, -0.003]}
            rotation={[-0.019, -0.003, -3.076]}
          >
            <primitive
              object={nodes.LeftLeg_59}
              position={[0, 0.458, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <primitive
                object={nodes.LeftFoot_58}
                position={[0, 0.444, 0]}
                rotation={[1.065, 0.03, -0.014]}
              >
                <primitive
                  object={nodes.LeftToeBase_57}
                  position={[0, 0.149, 0]}
                  rotation={[0.546, -0.074, 0.059]}
                >
                  <primitive
                    object={nodes.LeftToe_End_56}
                    position={[0, 0.099, 0]}
                    rotation={[-0.546, 1.542, 0.581]}
                  />
                </primitive>
              </primitive>
            </primitive>
          </primitive>
          <primitive
            object={nodes.RightUpLeg_65}
            position={[-0.095, 0.005, -0.003]}
            rotation={[-0.019, 0.004, 3.076]}
          >
            <primitive
              object={nodes.RightLeg_64}
              position={[0, 0.458, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <primitive
                object={nodes.RightFoot_63}
                position={[0, 0.444, 0]}
                rotation={[1.065, -0.03, 0.014]}
              >
                <primitive
                  object={nodes.RightToeBase_62}
                  position={[0, 0.149, 0]}
                  rotation={[0.546, 0.074, -0.059]}
                >
                  <primitive
                    object={nodes.RightToe_End_61}
                    position={[0, 0.099, 0]}
                    rotation={[-0.546, -1.542, -0.581]}
                  />
                </primitive>
              </primitive>
            </primitive>
          </primitive>
        </primitive>
      </primitive>
      <skinnedMesh
        geometry={nodes.Object_7.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.Object_7.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_9.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.Object_9.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_11.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Object_11.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_13.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Object_13.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_15.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Object_15.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_17.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Object_17.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_19.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Object_19.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_21.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Object_21.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_23.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Object_23.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/models/character/male/male-transformed.glb");
