/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 calligraphy_school.glb -T --shadows -j 
Files: calligraphy_school.glb [5.66MB] > /Users/eax./Documents/practice/class_caligraphy/calligraphy_school-transformed.glb [777.46KB] (86%)
Author: annzep (https://sketchfab.com/annzep)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/calligraphy-school-74c085a8ccd5491eb4120cec7c13500b
Title: Calligraphy School
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/class_caligraphy/calligraphy_school-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.pCylinder3_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.512, 0.419, -0.377]} scale={[0.06, 0.279, 0.06]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder3_phong50_0.geometry} material={materials.PaletteMaterial002} position={[0.512, 0.419, -0.377]} scale={[0.06, 0.279, 0.06]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube2_phong31_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.838, 0]} scale={[1.184, 0.203, 1.024]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube2_phong44_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.838, 0]} scale={[1.184, 0.203, 1.024]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube2_phong43_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.838, 0]} scale={[1.184, 0.203, 1.024]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder42_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.512, 0.126, -0.377]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder46_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.512, 0.126, 0.373]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder49_phong2_0.geometry} material={materials.PaletteMaterial001} position={[-0.52, 0.126, -0.377]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder51_phong2_0.geometry} material={materials.PaletteMaterial001} position={[-0.52, 0.126, 0.373]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder42_phong51_0.geometry} material={materials.PaletteMaterial002} position={[0.512, 0.126, -0.377]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder46_phong51_0.geometry} material={materials.PaletteMaterial002} position={[0.512, 0.126, 0.373]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder49_phong51_0.geometry} material={materials.PaletteMaterial002} position={[-0.52, 0.126, -0.377]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder51_phong51_0.geometry} material={materials.PaletteMaterial002} position={[-0.52, 0.126, 0.373]} scale={[0.076, 0.027, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder43_phong50_0.geometry} material={materials.PaletteMaterial002} position={[0.512, 0.7, -0.377]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder45_phong50_0.geometry} material={materials.PaletteMaterial002} position={[0.512, 0.7, 0.373]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder47_phong50_0.geometry} material={materials.PaletteMaterial002} position={[-0.52, 0.711, -0.377]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder52_phong50_0.geometry} material={materials.PaletteMaterial002} position={[-0.52, 0.7, 0.373]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder43_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.512, 0.7, -0.377]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder45_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.512, 0.7, 0.373]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder47_phong2_0.geometry} material={materials.PaletteMaterial001} position={[-0.52, 0.711, -0.377]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder52_phong2_0.geometry} material={materials.PaletteMaterial001} position={[-0.52, 0.7, 0.373]} scale={[0.076, 0.039, 0.076]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder44_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.512, 0.419, 0.373]} scale={[0.06, 0.279, 0.06]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder48_phong2_0.geometry} material={materials.PaletteMaterial001} position={[-0.52, 0.419, -0.377]} scale={[0.06, 0.279, 0.06]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder50_phong2_0.geometry} material={materials.PaletteMaterial001} position={[-0.52, 0.419, 0.373]} scale={[0.06, 0.279, 0.06]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube17_lambert1_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.006, -0.439]} rotation={[0, 0, Math.PI / 2]} scale={[0.02, 0.915, 0.014]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube23_phong8_0.geometry} material={materials.PaletteMaterial003} position={[-0.008, 0.362, -0.45]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.282, 0.282, 0.071]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube24_phong8_0.geometry} material={materials.PaletteMaterial003} position={[-0.543, 0.362, -0.072]} rotation={[0, -Math.PI / 2, 0]} scale={[0.282, 0.282, 0.071]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube25_phong27_0.geometry} material={materials.PaletteMaterial004} position={[0.515, 0.61, 0]} scale={[0.028, 0.048, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube49_phong27_0.geometry} material={materials.PaletteMaterial004} position={[0.515, 0.238, 0]} scale={[0.031, 0.025, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube25_phong45_0.geometry} material={materials.PaletteMaterial002} position={[0.515, 0.61, 0]} scale={[0.028, 0.048, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube49_phong45_0.geometry} material={materials.PaletteMaterial002} position={[0.515, 0.238, 0]} scale={[0.031, 0.025, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube25_phong46_0.geometry} material={materials.PaletteMaterial002} position={[0.515, 0.61, 0]} scale={[0.028, 0.048, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube49_phong46_0.geometry} material={materials.PaletteMaterial002} position={[0.515, 0.238, 0]} scale={[0.031, 0.025, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube26_phong46_0.geometry} material={materials.PaletteMaterial002} position={[0.515, 0.643, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.048, 0.048, 0.216]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube26_phong27_0.geometry} material={materials.PaletteMaterial004} position={[0.515, 0.643, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.048, 0.048, 0.216]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube35_phong46_0.geometry} material={materials.PaletteMaterial002} position={[-0.36, 0.61, 0.377]} rotation={[0, -Math.PI / 2, 0]} scale={[0.028, 0.048, 0.481]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube40_phong46_0.geometry} material={materials.PaletteMaterial002} position={[0.348, 0.61, 0.377]} rotation={[0, Math.PI / 2, 0]} scale={[0.028, 0.048, 0.481]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube35_phong45_0.geometry} material={materials.PaletteMaterial002} position={[-0.36, 0.61, 0.377]} rotation={[0, -Math.PI / 2, 0]} scale={[0.028, 0.048, 0.481]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube40_phong45_0.geometry} material={materials.PaletteMaterial002} position={[0.348, 0.61, 0.377]} rotation={[0, Math.PI / 2, 0]} scale={[0.028, 0.048, 0.481]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube35_phong27_0.geometry} material={materials.PaletteMaterial004} position={[-0.36, 0.61, 0.377]} rotation={[0, -Math.PI / 2, 0]} scale={[0.028, 0.048, 0.481]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube40_phong27_0.geometry} material={materials.PaletteMaterial004} position={[0.348, 0.61, 0.377]} rotation={[0, Math.PI / 2, 0]} scale={[0.028, 0.048, 0.481]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube36_phong46_0.geometry} material={materials.PaletteMaterial002} position={[-0.187, 0.664, 0.377]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.048, 0.048, 0.2]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube39_phong46_0.geometry} material={materials.PaletteMaterial002} position={[0.176, 0.664, 0.377]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.048, 0.048, 0.2]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube36_phong27_0.geometry} material={materials.PaletteMaterial004} position={[-0.187, 0.664, 0.377]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.048, 0.048, 0.2]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube39_phong27_0.geometry} material={materials.PaletteMaterial004} position={[0.176, 0.664, 0.377]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.048, 0.048, 0.2]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube50_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.515, 0.107, 0]} scale={[0.031, 0.025, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube203_phong2_0.geometry} material={materials.PaletteMaterial001} position={[-0.507, 0.107, 0]} scale={[0.031, 0.025, 0.648]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube204_phong2_0.geometry} material={materials.PaletteMaterial001} position={[0.005, 0.107, -0.414]} rotation={[0, Math.PI / 2, 0]} scale={[0.031, 0.025, 0.921]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder113_phong27_0.geometry} material={materials.PaletteMaterial004} position={[0.515, 0.176, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.014, 0.342, 0.014]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube63_phong13_0.geometry} material={materials.PaletteMaterial002} scale={[1.156, 0.116, 0.931]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube64_phong55_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.085, 0]} scale={[1.184, 0.042, 0.954]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube267_phong55_0.geometry} material={materials.PaletteMaterial002} position={[0, -0.084, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.184, 0.042, 0.954]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube64_phong24_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.085, 0]} scale={[1.184, 0.042, 0.954]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube267_phong24_0.geometry} material={materials.PaletteMaterial002} position={[0, -0.084, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.184, 0.042, 0.954]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube64_phong56_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.085, 0]} scale={[1.184, 0.042, 0.954]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube267_phong56_0.geometry} material={materials.PaletteMaterial002} position={[0, -0.084, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.184, 0.042, 0.954]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube66_phong13_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.003, -0.016]} scale={[0.204, 0.29, 0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube66_phong33_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.003, -0.016]} scale={[0.204, 0.29, 0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube66_phong35_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.003, -0.016]} scale={[0.204, 0.29, 0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube66_phong34_0.geometry} material={materials.PaletteMaterial002} position={[0, 0.003, -0.016]} scale={[0.204, 0.29, 0.29]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube67_phong24_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube67_phong57_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube67_phong55_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube67_phong36_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1485_phong4_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1499_phong4_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1506_phong4_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1492_phong4_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1486_phong3_0.geometry} material={materials.PaletteMaterial005} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1500_phong3_0.geometry} material={materials.PaletteMaterial005} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1507_phong3_0.geometry} material={materials.PaletteMaterial005} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1493_phong3_0.geometry} material={materials.PaletteMaterial005} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1487_phong3_0.geometry} material={materials.PaletteMaterial005} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1501_phong3_0.geometry} material={materials.PaletteMaterial005} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1508_phong3_0.geometry} material={materials.PaletteMaterial005} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1494_phong3_0.geometry} material={materials.PaletteMaterial005} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1488_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1502_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1509_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1495_phong1_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1488_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1502_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1509_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1495_phong40_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1489_phong4_0.geometry} material={materials.PaletteMaterial002} position={[0, -0.336, 0]} scale={[0.282, 0.45, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1503_phong4_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, -0.336, 0]} scale={[-0.282, 0.45, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1510_phong4_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, -0.336, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.282, 0.45, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1496_phong4_0.geometry} material={materials.PaletteMaterial002} position={[0, -0.336, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.45, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1490_phong3_0.geometry} material={materials.PaletteMaterial005} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1504_phong3_0.geometry} material={materials.PaletteMaterial005} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1511_phong3_0.geometry} material={materials.PaletteMaterial005} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1497_phong3_0.geometry} material={materials.PaletteMaterial005} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1491_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1498_phong1_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1491_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1498_phong40_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.006]} rotation={[-Math.PI, 0, Math.PI]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1505_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1505_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={[-0.282, 0.282, 0.282]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1512_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1512_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube69_phong28_0.geometry} material={materials.PaletteMaterial002} position={[0.338, -0.097, 0.547]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube71_phong29_0.geometry} material={materials.PaletteMaterial002} position={[0.478, -0.098, 0.553]} rotation={[0, 1.553, 0]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube72_phong20_0.geometry} material={materials.PaletteMaterial002} position={[0.381, -0.098, 0.679]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube73_phong28_0.geometry} material={materials.PaletteMaterial002} position={[0.526, -0.097, 0.651]} scale={[0.116, 0.009, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube74_phong29_0.geometry} material={materials.PaletteMaterial002} position={[0.435, -0.096, 0.765]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube75_phong28_0.geometry} material={materials.PaletteMaterial002} position={[0.313, -0.097, 0.748]} rotation={[0, 0.716, 0]} scale={[0.116, 0.009, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube76_phong28_0.geometry} material={materials.PaletteMaterial002} position={[0.379, -0.098, 0.856]} rotation={[0, 0.716, 0]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube77_phong28_0.geometry} material={materials.PaletteMaterial002} position={[0.626, -0.099, 0.547]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube78_phong29_0.geometry} material={materials.PaletteMaterial002} position={[0.612, -0.098, 0.594]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube79_phong20_0.geometry} material={materials.PaletteMaterial002} position={[0.547, -0.098, 0.771]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube80_phong28_0.geometry} material={materials.PaletteMaterial002} position={[0.692, -0.098, 0.732]} rotation={[-Math.PI, 0.14, -Math.PI]} scale={[0.116, 0.007, 0.116]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube82_phong30_0.geometry} material={materials.PaletteMaterial002} position={[0.255, -0.084, 0.826]} rotation={[0, -0.122, 0]} scale={[0.053, 0.03, 0.029]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1935_phong5_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1936_phong5_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1937_phong49_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder127_phong9_0.geometry} material={materials.PaletteMaterial006} position={[0.489, 0.036, 0.71]} rotation={[0, Math.PI / 4, Math.PI / 2]} scale={[0.009, 0.002, 0.009]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder128_phong9_0.geometry} material={materials.PaletteMaterial006} position={[0.549, 0.036, 0.65]} rotation={[0, Math.PI / 4, Math.PI / 2]} scale={[0.009, 0.002, 0.009]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube227_phong31_0.geometry} material={materials.PaletteMaterial002} position={[0.16, 0.914, 0.406]} rotation={[0.436, 0, 0]} scale={[0.04, 0.096, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube228_phong31_0.geometry} material={materials.PaletteMaterial002} position={[-0.148, 0.914, 0.406]} rotation={[0.436, 0, 0]} scale={[0.04, 0.096, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1513_phong6_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1514_phong6_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1515_phong6_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1516_phong6_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1517_phong6_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1518_phong6_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1519_phong31_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1519_phong43_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1520_phong43_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1520_phong31_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1521_phong43_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1521_phong31_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1522_phong31_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1522_phong43_0.geometry} material={materials.PaletteMaterial002} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1523_phong7_0.geometry} material={materials.PaletteMaterial007} position={[-0.003, -0.062, 0.169]} rotation={[-0.175, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1484_phong65_0.geometry} material={materials.PaletteMaterial002} position={[0.006, -0.036, -0.025]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1484_phong16_0.geometry} material={materials.PaletteMaterial008} position={[0.006, -0.036, -0.025]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1540_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1540_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1541_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1541_phong64_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1542_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1542_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1543_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1543_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1544_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1545_phong18_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1545_phong62_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1546_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1546_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1547_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1547_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1548_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1548_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1549_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1549_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1550_phong17_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1550_phong63_0.geometry} material={materials.PaletteMaterial002} position={[0.166, 0, 0.131]} rotation={[0, -0.262, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube236_phong15_0.geometry} material={materials.PaletteMaterial002} position={[-0.229, 0.113, 0.019]} rotation={[0, Math.PI / 2, 0]} scale={[0.728, 0.016, 0.416]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube253_phong15_0.geometry} material={materials.PaletteMaterial002} position={[0.223, 0.113, 0.019]} rotation={[0, Math.PI / 2, 0]} scale={[0.728, 0.016, 0.416]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube237_phong14_0.geometry} material={materials.PaletteMaterial009} position={[-0.12, 0.13, 0.24]} rotation={[0, 0.087, 0]} scale={[0.152, 0.016, 0.144]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube258_phong14_0.geometry} material={materials.PaletteMaterial009} position={[-0.127, 0.13, -0.168]} rotation={[0, Math.PI / 9, 0]} scale={[0.152, 0.016, 0.144]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube259_phong14_0.geometry} material={materials.PaletteMaterial009} position={[0.276, 0.13, -0.194]} rotation={[0, -0.262, 0]} scale={[0.152, 0.016, 0.144]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube260_phong14_0.geometry} material={materials.PaletteMaterial009} position={[0.322, 0.13, 0.187]} rotation={[0, 0.175, 0]} scale={[0.152, 0.016, 0.144]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1806_phong9_0.geometry} material={materials.PaletteMaterial006} position={[-0.02, -0.015, -0.456]} rotation={[0, 0.262, 0]} scale={[0.301, 0.321, 0.301]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder140_phong7_0.geometry} material={materials.PaletteMaterial007} position={[-0.056, 0.001, -0.009]} scale={[0.282, 0.282, 0.324]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder147_phong7_0.geometry} material={materials.PaletteMaterial007} position={[-0.111, 0.001, -0.445]} rotation={[0, Math.PI / 9, 0]} scale={[0.282, 0.282, 0.324]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder149_phong7_0.geometry} material={materials.PaletteMaterial007} position={[0.41, 0.001, -0.408]} rotation={[0, -0.175, 0]} scale={[0.282, 0.282, 0.324]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder151_phong7_0.geometry} material={materials.PaletteMaterial007} position={[0.306, 0.001, -0.071]} rotation={[0, Math.PI / 9, 0]} scale={[0.282, 0.282, 0.324]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1532_phong11_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1536_phong11_0.geometry} material={materials.PaletteMaterial002} position={[-0.188, 0, -0.51]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1528_phong11_0.geometry} material={materials.PaletteMaterial002} position={[0.35, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1524_phong11_0.geometry} material={materials.PaletteMaterial002} position={[0.256, 0, -0.149]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1533_phong10_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1537_phong10_0.geometry} material={materials.PaletteMaterial002} position={[-0.188, 0, -0.51]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1529_phong10_0.geometry} material={materials.PaletteMaterial002} position={[0.35, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1525_phong10_0.geometry} material={materials.PaletteMaterial002} position={[0.256, 0, -0.149]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1534_phong61_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1538_phong61_0.geometry} material={materials.PaletteMaterial002} position={[-0.188, 0, -0.51]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1530_phong61_0.geometry} material={materials.PaletteMaterial002} position={[0.35, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1526_phong61_0.geometry} material={materials.PaletteMaterial002} position={[0.256, 0, -0.149]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1535_phong12_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1539_phong12_0.geometry} material={materials.PaletteMaterial002} position={[-0.188, 0, -0.51]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1531_phong12_0.geometry} material={materials.PaletteMaterial002} position={[0.35, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1527_phong12_0.geometry} material={materials.PaletteMaterial002} position={[0.256, 0, -0.149]} rotation={[0, Math.PI / 4, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1551_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1551_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1552_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1552_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1553_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1553_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1554_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1554_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1555_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1555_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1556_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1556_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1557_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1558_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1558_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1559_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1560_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1561_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1562_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1563_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1563_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1564_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1565_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1566_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1567_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1568_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1569_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1570_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1571_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1572_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1573_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1574_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1575_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1576_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1577_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1577_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1578_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1579_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1580_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1581_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1582_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1583_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1584_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1585_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1586_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1587_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1588_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1589_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1590_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1591_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1592_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1593_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1594_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1595_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1596_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1597_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1598_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1599_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1599_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1600_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1601_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1602_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1603_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1604_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1605_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1605_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1606_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1606_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1607_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1608_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1609_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1610_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1611_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1612_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1612_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1613_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1614_phong42_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1614_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1614_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1615_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1616_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1616_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1617_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1617_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1618_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1618_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1619_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1619_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1620_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1620_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1621_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1621_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1622_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1622_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1623_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1623_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1624_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1624_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1625_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1625_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1626_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1626_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1627_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1627_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1628_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1628_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1629_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1630_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1631_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1632_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1633_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1634_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1635_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1636_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1637_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1638_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1639_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1640_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1641_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1642_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1643_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1644_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1645_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1646_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1647_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1648_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1649_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1650_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1651_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1652_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1652_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1653_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1654_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1655_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1655_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1656_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1657_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1657_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1658_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1658_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1659_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1659_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1660_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1660_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1661_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1661_phong41_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1662_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1662_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1663_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1663_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1664_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1664_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1665_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1665_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1666_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1666_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1667_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1667_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1668_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1668_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1669_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1669_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1670_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1671_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1671_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1672_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1673_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1674_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1675_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1676_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1677_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1678_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1679_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1680_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1681_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1682_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1683_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1684_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1685_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1686_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1687_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1688_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1689_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1690_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1691_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1692_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1693_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1694_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1695_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1696_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1697_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1698_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1699_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1700_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1701_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1702_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1703_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1704_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1704_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1705_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1705_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1706_phong1_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1706_phong40_0.geometry} material={materials.PaletteMaterial002} position={[-0.01, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1707_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1708_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1709_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1710_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1711_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1712_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1713_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1714_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1715_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1716_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1717_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1718_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1719_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1720_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1721_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1722_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1723_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1724_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1725_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1726_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1727_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1728_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1729_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1730_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1731_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1732_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1733_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1734_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1735_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1736_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1737_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1738_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1739_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1740_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1741_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1742_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1743_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1744_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1745_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1746_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1747_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1748_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1749_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1750_phong1_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1750_phong40_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1751_phong1_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0.006]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1751_phong40_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0.006]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1752_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1752_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1753_phong1_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1753_phong40_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1754_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1754_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1755_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1755_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1756_phong1_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1756_phong40_0.geometry} material={materials.PaletteMaterial002} position={[0.009, 0, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1757_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1757_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1758_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1758_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1759_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1759_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1760_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1760_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1761_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1762_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1762_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1763_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1764_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1765_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1765_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1766_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1766_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1767_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1768_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1768_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1769_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1770_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1771_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1772_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1772_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1773_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1774_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1775_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1776_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1777_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1778_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1779_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1780_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1780_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1781_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1782_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1783_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1783_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1784_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1785_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1786_phong26_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1787_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1788_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1788_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1789_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1789_phong40_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1790_phong1_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1791_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1792_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1793_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1794_phong25_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder154_phong7_0.geometry} material={materials.PaletteMaterial007} position={[0.179, 0.237, 0.671]} rotation={[-Math.PI, Math.PI / 4, -1.745]} scale={[0.247, 0.282, 0.273]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1839_phong46_0.geometry} material={materials.PaletteMaterial002} position={[1.03, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1839_phong27_0.geometry} material={materials.PaletteMaterial004} position={[1.03, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1840_phong45_0.geometry} material={materials.PaletteMaterial002} position={[1.03, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1840_phong46_0.geometry} material={materials.PaletteMaterial002} position={[1.03, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1840_phong27_0.geometry} material={materials.PaletteMaterial004} position={[1.03, 0, -0.006]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube262_phong45_0.geometry} material={materials.PaletteMaterial002} position={[-0.002, 0, 0.754]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube262_phong46_0.geometry} material={materials.PaletteMaterial002} position={[-0.002, 0, 0.754]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pCube262_phong27_0.geometry} material={materials.PaletteMaterial004} position={[-0.002, 0, 0.754]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1842_phong46_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1842_phong27_0.geometry} material={materials.PaletteMaterial004} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1842_phong45_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1867_phong27_0.geometry} material={materials.PaletteMaterial004} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1867_phong45_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1867_phong46_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1934_phong27_0.geometry} material={materials.PaletteMaterial004} position={[-0.091, 0, -0.015]} rotation={[0, Math.PI / 2, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1934_phong45_0.geometry} material={materials.PaletteMaterial002} position={[-0.091, 0, -0.015]} rotation={[0, Math.PI / 2, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1934_phong46_0.geometry} material={materials.PaletteMaterial002} position={[-0.091, 0, -0.015]} rotation={[0, Math.PI / 2, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1951_phong9_0.geometry} material={materials.PaletteMaterial006} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1954_phong9_0.geometry} material={materials.PaletteMaterial006} position={[-0.083, 0, -0.458]} rotation={[0, 0.436, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1955_phong9_0.geometry} material={materials.PaletteMaterial006} position={[0.361, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1956_phong9_0.geometry} material={materials.PaletteMaterial006} position={[0.363, 0, -0.092]} rotation={[0, Math.PI / 9, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1951_phong58_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1954_phong58_0.geometry} material={materials.PaletteMaterial002} position={[-0.083, 0, -0.458]} rotation={[0, 0.436, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1955_phong58_0.geometry} material={materials.PaletteMaterial002} position={[0.361, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1956_phong58_0.geometry} material={materials.PaletteMaterial002} position={[0.363, 0, -0.092]} rotation={[0, Math.PI / 9, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1951_phong60_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1954_phong60_0.geometry} material={materials.PaletteMaterial002} position={[-0.083, 0, -0.458]} rotation={[0, 0.436, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1955_phong60_0.geometry} material={materials.PaletteMaterial002} position={[0.361, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1956_phong60_0.geometry} material={materials.PaletteMaterial002} position={[0.363, 0, -0.092]} rotation={[0, Math.PI / 9, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1951_phong59_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1954_phong59_0.geometry} material={materials.PaletteMaterial002} position={[-0.083, 0, -0.458]} rotation={[0, 0.436, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1955_phong59_0.geometry} material={materials.PaletteMaterial002} position={[0.361, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1956_phong59_0.geometry} material={materials.PaletteMaterial002} position={[0.363, 0, -0.092]} rotation={[0, Math.PI / 9, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1951_phong32_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1954_phong32_0.geometry} material={materials.PaletteMaterial002} position={[-0.083, 0, -0.458]} rotation={[0, 0.436, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1955_phong32_0.geometry} material={materials.PaletteMaterial002} position={[0.361, 0, -0.468]} rotation={[0, 0.175, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1956_phong32_0.geometry} material={materials.PaletteMaterial002} position={[0.363, 0, -0.092]} rotation={[0, Math.PI / 9, 0]} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pasted__polySurface1449_phong58_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pasted__polySurface1449_phong59_0.geometry} material={materials.PaletteMaterial002} scale={0.282} />
      <mesh castShadow receiveShadow geometry={nodes.pasted__polySurface1449_phong9_0.geometry} material={materials.PaletteMaterial006} scale={0.282} />
      <instancedMesh args={[nodes.pCylinder114_phong27_0.geometry, materials.PaletteMaterial004, 5]} castShadow receiveShadow instanceMatrix={nodes.pCylinder114_phong27_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube52_phong19_0.geometry, materials.PaletteMaterial002, 5]} castShadow receiveShadow instanceMatrix={nodes.pCube52_phong19_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube52_phong53_0.geometry, materials.PaletteMaterial002, 5]} castShadow receiveShadow instanceMatrix={nodes.pCube52_phong53_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube52_phong54_0.geometry, materials.PaletteMaterial002, 5]} castShadow receiveShadow instanceMatrix={nodes.pCube52_phong54_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube81_phong21_0.geometry, materials.PaletteMaterial002, 54]} castShadow receiveShadow instanceMatrix={nodes.pCube81_phong21_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube85_phong30_0.geometry, materials.PaletteMaterial002, 34]} castShadow receiveShadow instanceMatrix={nodes.pCube85_phong30_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube179_phong22_0.geometry, materials.PaletteMaterial002, 11]} castShadow receiveShadow instanceMatrix={nodes.pCube179_phong22_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1938_phong5_0.geometry, materials.PaletteMaterial002, 6]} castShadow receiveShadow instanceMatrix={nodes.polySurface1938_phong5_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1938_phong52_0.geometry, materials.PaletteMaterial002, 6]} castShadow receiveShadow instanceMatrix={nodes.polySurface1938_phong52_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/class_caligraphy/calligraphy_school-transformed.glb')
