/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 japanese_classroom.glb -T -j 
Files: japanese_classroom.glb [19.97MB] > /Users/eax./Documents/practice/class/japanese_classroom-transformed.glb [521.43KB] (97%)
Author: T I A N (https://sketchfab.com/Tian96)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-classroom-2a1e3b294c1e4e91bed794bfa520c4f4
Title: Japanese Classroom
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('models/class/japanese_classroom-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MARCO_DER_N_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.MARCO_DER_N2_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.468, 0, 0]} scale={[-0.131, 0.132, 0.132]} />
      <mesh geometry={nodes.MARCON_INT_1_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.MARCON_INT_5_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.479, -0.003, 0]} scale={[-0.131, 0.132, 0.132]} />
      <mesh geometry={nodes.MARCO_INT_3_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.MARCO_INT_7_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.493, 0, 0]} scale={[-0.131, 0.132, 0.132]} />
      <mesh geometry={nodes.PUERTA_1_StingrayPBS9_0.geometry} material={materials.StingrayPBS9} position={[0, 0, -0.024]} scale={0.132} />
      <mesh geometry={nodes.PUERTA_3_StingrayPBS9_0.geometry} material={materials.StingrayPBS9} position={[-0.483, 0, 0.1]} scale={[-0.132, 0.132, 0.132]} />
      <mesh geometry={nodes.PUERTA_4_StingrayPBS9_0.geometry} material={materials.StingrayPBS9} position={[-9.466, 0, 0.1]} scale={[-0.132, 0.132, 0.132]} />
      <mesh geometry={nodes.PUERTA_5_StingrayPBS9_0.geometry} material={materials.StingrayPBS9} position={[-8.983, 0, -0.024]} scale={0.132} />
      <mesh geometry={nodes.VENTANA_1_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[0, 0, -0.035]} scale={0.132} />
      <mesh geometry={nodes.VENTANA_14_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-8.312, -0.003, -0.022]} scale={[-0.131, 0.132, 0.132]} />
      <mesh geometry={nodes.VENTANA_15_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-1.169, 0, 0.018]} scale={0.132} />
      <mesh geometry={nodes.VENTANA_20_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.479, -0.003, 0.031]} scale={[-0.131, 0.132, 0.132]} />
      <mesh geometry={nodes.MARCON_INT_2_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.MARCON_INT_6_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.459, -0.004, 0]} scale={[-0.13, 0.132, 0.132]} />
      <mesh geometry={nodes.VENTANA_5_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-0.003, 0, -0.061]} scale={0.132} />
      <mesh geometry={nodes.VENTANA_6_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.VENTANA_12_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-8.31, 0, 0]} scale={[-0.131, 0.132, 0.132]} />
      <mesh geometry={nodes.VENTANA_17_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-1.187, 0, 0.054]} scale={0.132} />
      <mesh geometry={nodes.VENTANA_19_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.489, 0, 0.054]} scale={[-0.131, 0.132, 0.132]} />
      <mesh geometry={nodes.GRIPPUERTA_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[0, 0, -0.024]} scale={0.132} />
      <mesh geometry={nodes.GRIPPUERTA2_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-0.484, 0, 0.103]} scale={[-0.132, 0.132, 0.132]} />
      <mesh geometry={nodes.GRIPPUERTA3_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.467, 0, 0.103]} scale={[-0.132, 0.132, 0.132]} />
      <mesh geometry={nodes.GRIPPUERTA4_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-8.983, 0, -0.024]} scale={0.132} />
      <mesh geometry={nodes.VENTANA_13_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-8.278, -0.005, -0.056]} scale={[-0.13, 0.132, 0.132]} />
      <mesh geometry={nodes.VENTANA_16_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-1.199, 0, -0.009]} scale={0.132} />
      <mesh geometry={nodes.VENTANA_18_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.456, -0.005, -0.004]} scale={[-0.13, 0.132, 0.132]} />
      <mesh geometry={nodes.MARCO_IZQ_N_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.MARCO_IZQ_N2_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-6.345, 0, 0]} scale={0.132} />
      <mesh geometry={nodes.MARCO_INT_1_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.MARCO_INT_9_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-2.663, 0, 0]} scale={[0.134, 0.132, 0.132]} />
      <mesh geometry={nodes.MARCO_INT_10_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.008, 0, 0]} scale={[0.134, 0.132, 0.132]} />
      <mesh geometry={nodes.MARCO_INT_12_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-6.345, 0, 0]} scale={0.132} />
      <mesh geometry={nodes.MARCO_INT_2_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.MARCO_INT_8_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-2.663, 0, 0]} scale={[0.134, 0.132, 0.132]} />
      <mesh geometry={nodes.MARCO_INT_11_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-6.345, 0, 0]} scale={0.132} />
      <mesh geometry={nodes.MARCO_INT_13_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-9.008, 0, 0]} scale={[0.134, 0.132, 0.132]} />
      <mesh geometry={nodes.IZQ_StingrayPBS2_0.geometry} material={materials.StingrayPBS2} position={[-4.736, 1.577, -1.053]} scale={[12.63, 3.158, 6.315]} />
      <mesh geometry={nodes.DER_StingrayPBS2_0.geometry} material={materials.StingrayPBS2} position={[-4.736, 1.577, -1.053]} scale={[12.63, 3.158, 6.315]} />
      <mesh geometry={nodes.FLOOR_StingrayPBS10_0.geometry} material={materials.StingrayPBS10} position={[-4.736, 1.623, -3.158]} scale={[12.63, 3.158, 6.315]} />
      <mesh geometry={nodes.NORTHANDSOUTH_StingrayPBS2_0.geometry} material={materials.StingrayPBS2} position={[-4.736, 1.577, -3.158]} scale={[12.63, 3.158, 6.315]} />
      <mesh geometry={nodes.BORDE_METAL_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-4.736, 1.577, -3.158]} scale={[12.63, 3.158, 6.315]} />
      <mesh geometry={nodes.DETALLE_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[-4.736, 1.577, -3.158]} scale={[12.63, 3.158, 6.315]} />
      <mesh geometry={nodes.MARCO_GRANDE_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} scale={0.132} />
      <mesh geometry={nodes.VERDE_GRANDE_StingrayPBS7_0.geometry} material={materials.StingrayPBS7} scale={0.132} />
      <mesh geometry={nodes.MARCO_CHICO_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} scale={0.132} />
      <mesh geometry={nodes.MARCO_CHICO2_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} position={[0, 0, -6.91]} scale={[0.132, 0.132, 0.129]} />
      <mesh geometry={nodes.VERDE_CHICO_StingrayPBS7_0.geometry} material={materials.StingrayPBS7} scale={0.132} />
      <mesh geometry={nodes.VERDE_CHICO2_StingrayPBS7_0.geometry} material={materials.StingrayPBS7} position={[0, 0, -6.91]} scale={[0.132, 0.132, 0.129]} />
      <mesh geometry={nodes.TRAS_CORCHO1_StingrayPBS11_0.geometry} material={materials.StingrayPBS11} scale={0.132} />
      <mesh geometry={nodes.TRAS_CORCHO3_StingrayPBS11_0.geometry} material={materials.StingrayPBS11} position={[0, 0, -4.228]} scale={0.132} />
      <mesh geometry={nodes.TRAS_MARCO_C_1_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} scale={0.132} />
      <mesh geometry={nodes.TRAS_MARCO_C_3_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} position={[0, 0, -4.228]} scale={0.132} />
      <mesh geometry={nodes.TRAS_GRANDE_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} scale={0.132} />
      <mesh geometry={nodes.TRAS_VERDE_StingrayPBS7_0.geometry} material={materials.StingrayPBS7} scale={0.132} />
      <mesh geometry={nodes.BASE_METAL_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} scale={0.132} />
      <mesh geometry={nodes.BASE_MADERA_StingrayPBS4_0.geometry} material={materials.StingrayPBS4} scale={0.132} />
      <mesh geometry={nodes.METAL_PROF_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} scale={0.132} />
      <mesh geometry={nodes.MADERA_PROF_StingrayPBS5_0.geometry} material={materials.StingrayPBS5} scale={0.132} />
      <mesh geometry={nodes.LOCKER_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} scale={0.132} />
      <mesh geometry={nodes.CALENTADOR_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} scale={0.132} />
      <mesh geometry={nodes.MUEBLECHIQUITO_StingrayPBS6_0.geometry} material={materials.StingrayPBS6} position={[-0.077, 0.044, 0]} scale={0.132} />
      <mesh geometry={nodes.MUEBLET2_StingrayPBS4_0.geometry} material={materials.StingrayPBS4} position={[0, 0.053, 0]} scale={0.132} />
      <mesh geometry={nodes.ROOFpolySurface21_PARED_0.geometry} material={materials.PARED} position={[-4.736, 1.65, -3.158]} scale={[12.63, 3.158, 6.315]} />
      <mesh geometry={nodes.LAMPARAS_StingrayPBS1_0.geometry} material={materials.StingrayPBS1} position={[0, 0.729, 0]} scale={[0.132, 0.095, 0.132]} />
      {/* <instancedMesh args={[nodes.VENTANA_1_StingrayPBS1_0_1.geometry, materials.StingrayPBS1, 12]} instanceMatrix={nodes.VENTANA_1_StingrayPBS1_0_1.instanceMatrix} /> */}
      <instancedMesh args={[nodes.VENTANA_4_StingrayPBS1_0.geometry, materials.StingrayPBS1, 11]} instanceMatrix={nodes.VENTANA_4_StingrayPBS1_0.instanceMatrix} />
      <instancedMesh args={[nodes.MESAFINALPATAS_D_StingrayPBS6_0.geometry, materials.StingrayPBS6, 25]} instanceMatrix={nodes.MESAFINALPATAS_D_StingrayPBS6_0.instanceMatrix} />
      <instancedMesh args={[nodes.MESAFINALPATAS_T_StingrayPBS6_0.geometry, materials.StingrayPBS6, 25]} instanceMatrix={nodes.MESAFINALPATAS_T_StingrayPBS6_0.instanceMatrix} />
      <instancedMesh args={[nodes.MESAFINALEXTRA_StingrayPBS6_0.geometry, materials.StingrayPBS6, 25]} instanceMatrix={nodes.MESAFINALEXTRA_StingrayPBS6_0.instanceMatrix} />
      <instancedMesh args={[nodes.MESAFINALPATAS_D1_StingrayPBS6_0.geometry, materials.StingrayPBS6, 50]} instanceMatrix={nodes.MESAFINALPATAS_D1_StingrayPBS6_0.instanceMatrix} />
      <instancedMesh args={[nodes.RESPALDO1_StingrayPBS5_0.geometry, materials.StingrayPBS5, 25]} instanceMatrix={nodes.RESPALDO1_StingrayPBS5_0.instanceMatrix} />
      <instancedMesh args={[nodes.ASIENTO1_StingrayPBS5_0.geometry, materials.StingrayPBS5, 25]} instanceMatrix={nodes.ASIENTO1_StingrayPBS5_0.instanceMatrix} />
      <instancedMesh args={[nodes.MESAFINALGANCHO_I_StingrayPBS6_0.geometry, materials.StingrayPBS6, 50]} instanceMatrix={nodes.MESAFINALGANCHO_I_StingrayPBS6_0.instanceMatrix} />
      <instancedMesh args={[nodes.MESAFINALUNION_StingrayPBS6_0.geometry, materials.StingrayPBS6, 25]} instanceMatrix={nodes.MESAFINALUNION_StingrayPBS6_0.instanceMatrix} />
      <instancedMesh args={[nodes.MESAFINALCAJON_StingrayPBS6_0.geometry, materials.StingrayPBS6, 25]} instanceMatrix={nodes.MESAFINALCAJON_StingrayPBS6_0.instanceMatrix} />
      <instancedMesh args={[nodes.TAPA4_StingrayPBS5_0.geometry, materials.StingrayPBS5, 25]} instanceMatrix={nodes.TAPA4_StingrayPBS5_0.instanceMatrix} />
      <instancedMesh args={[nodes.VENTANA_CRISTAL_VENTANAS_0.geometry, materials.VENTANAS, 32]} instanceMatrix={nodes.VENTANA_CRISTAL_VENTANAS_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('models/class/japanese_classroom-transformed.glb')
