/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 colourd_scene.glb -T -j --shadows 
Files: colourd_scene.glb [39.33MB] > /Users/eax./Documents/practice/snow/colourd_scene-transformed.glb [1.95MB] (95%)
Author: ganzhugav (https://sketchfab.com/ganzhugav)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/colourdraftssimon-stalenhag-scene-8728b0b42c4e4fd7889d34a76966def1
Title: colourdrafts(Simon Stalenhag scene)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('models/snow/colourd_scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.polySurface282_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0.069, -0.079]} rotation={[0, 0, -0.069]} scale={[0.093, 0.04, 0.004]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface283_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.003, 0.069, -0.079]} scale={[0.093, 0.04, 0.005]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface286_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.009, 0.07, -0.081]} rotation={[0, 0, -0.343]} scale={[0.09, 0.051, 0.005]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface287_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.003, 0.051, -0.076]} rotation={[-0.061, -0.635, -0.559]} scale={[0.043, 0.033, 0.067]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface285_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.024, 0.069, -0.079]} rotation={[0, 0, -0.17]} scale={[0.093, 0.042, 0.005]} />
      <mesh castShadow receiveShadow geometry={nodes.pDisc2_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pDisc2_lambert36_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pDisc2_lambert37_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pDisc2_lambert20_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface280_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface280_lambert4_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface280_lambert11_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface280_lambert5_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface280_lambert21_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface280_lambert20_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube26_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube27_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.037, 0.064, -0.079]} rotation={[-Math.PI, -1.481, 1.672]} scale={[0.007, 0.004, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube28_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.005, 0.117, -0.079]} rotation={[-1.699, -0.236, 2.021]} scale={[0.003, 0.004, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube29_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.012, 0.115, -0.058]} rotation={[-1.833, 0.057, 0.745]} scale={[0.001, 0.003, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert24_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert5_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert6_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert4_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert20_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert23_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface396_lambert32_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, -0.002, 0.022]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1137_blinn8_0.geometry} material={materials.PaletteMaterial001} position={[0.351, 0.038, -0.147]} rotation={[3.06, 1.41, -3.082]} scale={[0.008, 0.01, 0.009]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1137_blinn16_0.geometry} material={materials.PaletteMaterial001} position={[0.351, 0.038, -0.147]} rotation={[3.06, 1.41, -3.082]} scale={[0.008, 0.01, 0.009]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface542_blinn9_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface542_blinn10_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface542_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface542_blinn11_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface618_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.11, 0.025, -0.105]} rotation={[-2.789, 1.333, 2.757]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface618_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.11, 0.025, -0.105]} rotation={[-2.789, 1.333, 2.757]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2891_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.058, 0.038, -0.279]} rotation={[-2.805, -1.239, -2.94]} scale={[0.008, 0.006, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface618_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.11, 0.025, -0.105]} rotation={[-2.789, 1.333, 2.757]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface619_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[-0.005, 0.021, -0.033]} rotation={[-0.057, -0.077, -0.128]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface619_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[-0.005, 0.021, -0.033]} rotation={[-0.057, -0.077, -0.128]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface619_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.005, 0.021, -0.033]} rotation={[-0.057, -0.077, -0.128]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface878_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface879_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface882_lambert29_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface882_lambert6_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface882_lambert30_0.geometry} material={materials.PaletteMaterial002} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface882_lambert31_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface886_lambert29_0.geometry} material={materials.PaletteMaterial001} position={[0.098, -0.004, 0.186]} rotation={[-0.142, -0.515, -0.212]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface886_lambert6_0.geometry} material={materials.PaletteMaterial001} position={[0.098, -0.004, 0.186]} rotation={[-0.142, -0.515, -0.212]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface886_lambert30_0.geometry} material={materials.PaletteMaterial002} position={[0.098, -0.004, 0.186]} rotation={[-0.142, -0.515, -0.212]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface886_lambert31_0.geometry} material={materials.PaletteMaterial001} position={[0.098, -0.004, 0.186]} rotation={[-0.142, -0.515, -0.212]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface888_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.015, 0.008, -0.017]} rotation={[-0.134, 0.321, 0.078]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1766_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.302, 0.008, 0.012]} rotation={[-0.134, 0.321, 0.078]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface888_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.015, 0.008, -0.017]} rotation={[-0.134, 0.321, 0.078]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1766_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.302, 0.008, 0.012]} rotation={[-0.134, 0.321, 0.078]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface888_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.015, 0.008, -0.017]} rotation={[-0.134, 0.321, 0.078]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1766_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.302, 0.008, 0.012]} rotation={[-0.134, 0.321, 0.078]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube119_lambert28_0.geometry} material={materials.PaletteMaterial001} position={[0.026, 0.01, -0.015]} rotation={[0, -0.581, 0.097]} scale={[0.01, 0.008, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube137_lambert28_0.geometry} material={materials.PaletteMaterial001} position={[0.103, -0.004, 0.096]} rotation={[-Math.PI, 0.552, -Math.PI]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1131_lambert5_0.geometry} material={materials.PaletteMaterial001} position={[0.14, -0.043, -0.136]} rotation={[-0.046, -0.612, -0.042]} scale={0.016} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1131_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.14, -0.043, -0.136]} rotation={[-0.046, -0.612, -0.042]} scale={0.016} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1131_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.14, -0.043, -0.136]} rotation={[-0.046, -0.612, -0.042]} scale={0.016} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere1_lambert33_0.geometry} material={materials.PaletteMaterial001} position={[0.162, 0.096, 0.003]} rotation={[-0.401, -0.342, 0.85]} scale={0.024} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere1_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.162, 0.096, 0.003]} rotation={[-0.401, -0.342, 0.85]} scale={0.024} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere1_lambert32_0.geometry} material={materials.PaletteMaterial001} position={[0.162, 0.096, 0.003]} rotation={[-0.401, -0.342, 0.85]} scale={0.024} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere1_blinn8_0.geometry} material={materials.PaletteMaterial001} position={[0.162, 0.096, 0.003]} rotation={[-0.401, -0.342, 0.85]} scale={0.024} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere1_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.162, 0.096, 0.003]} rotation={[-0.401, -0.342, 0.85]} scale={0.024} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere1_lambert19_0.geometry} material={materials.PaletteMaterial001} position={[0.162, 0.096, 0.003]} rotation={[-0.401, -0.342, 0.85]} scale={0.024} />
      <mesh castShadow receiveShadow geometry={nodes.pCube158_lambert28_0.geometry} material={materials.PaletteMaterial001} position={[0.041, 0.081, -0.013]} rotation={[0.539, -0.952, 0.694]} scale={[0, 0.002, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube162_lambert28_0.geometry} material={materials.PaletteMaterial001} position={[0.053, 0.091, -0.015]} rotation={[-0.495, -1.249, -0.558]} scale={[0, 0.002, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube163_lambert28_0.geometry} material={materials.PaletteMaterial001} position={[0.068, 0.083, -0.016]} rotation={[3.112, -0.733, -2.713]} scale={[0, 0.002, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube167_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.167, 0.076, 0.012]} rotation={[-2.822, -1.129, 2.916]} scale={[0.02, 0.004, 0.014]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1739_blinn8_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1739_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1739_lambert18_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1739_lambert19_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1739_Default_Material_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1756_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.173, -0.002, 0.051]} rotation={[-0.017, 0.701, 0.042]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1760_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.332, -0.034, -0.358]} rotation={[2.975, 0.151, -3.098]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder11_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.154, 0.205, -0.207]} rotation={[1.892, -0.164, -0.303]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder11_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.154, 0.205, -0.207]} rotation={[1.892, -0.164, -0.303]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1759_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.16, 0.182, -0.203]} rotation={[-0.39, -0.168, 0.294]} scale={[0, 0.012, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1759_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.16, 0.182, -0.203]} rotation={[-0.39, -0.168, 0.294]} scale={[0, 0.012, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1758_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1761_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.124, 0.438, 0.086]} rotation={[0.638, -1.029, -2.38]} scale={0.014} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1769_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1772_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.212, 0.075, 0.079]} rotation={[0.274, -0.68, 1.895]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1771_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1771_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder18_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.154, 0.241, -0.213]} rotation={[0.101, 0.298, 0.325]} scale={[0, 0.002, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder18_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.154, 0.241, -0.213]} rotation={[0.101, 0.298, 0.325]} scale={[0, 0.002, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1789_blinn9_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1789_blinn17_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1789_blinn16_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1789_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube192_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.154, 0.242, -0.211]} rotation={[-1.519, -0.42, 0]} scale={[0, 0.004, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube193_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.154, 0.243, -0.211]} rotation={[-1.519, -0.332, -0.21]} scale={[0, 0.004, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1790_blinn8_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1790_blinn16_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder19_blinn17_0.geometry} material={materials.PaletteMaterial001} position={[0.153, 0.242, -0.212]} rotation={[-0.282, -0.004, 0.654]} scale={0} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1791_blinn17_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1791_blinn9_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1796_blinn17_0.geometry} material={materials.PaletteMaterial001} position={[0.355, 0.02, -0.064]} rotation={[0, 1.556, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1797_blinn17_0.geometry} material={materials.PaletteMaterial001} position={[0.355, 0.02, -0.064]} rotation={[0, 1.556, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1798_blinn17_0.geometry} material={materials.PaletteMaterial001} position={[0.355, 0.02, -0.064]} rotation={[0, 1.556, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1799_blinn17_0.geometry} material={materials.PaletteMaterial001} position={[0.357, -0.045, -0.064]} rotation={[0, 1.556, 0]} scale={[0.01, 0.013, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1964_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.064, -0.004, 0.009]} rotation={[-0.054, -0.283, 0.106]} scale={[0.014, 0.012, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2549_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.133, -0.019, -0.222]} rotation={[-0.341, 0.981, 0.074]} scale={0.012} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2892_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.197, 0.017, -0.232]} rotation={[-0.069, 0.895, 0.05]} scale={[0.007, 0.008, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1964_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.064, -0.004, 0.009]} rotation={[-0.054, -0.283, 0.106]} scale={[0.014, 0.012, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2549_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.133, -0.019, -0.222]} rotation={[-0.341, 0.981, 0.074]} scale={0.012} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2892_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.197, 0.017, -0.232]} rotation={[-0.069, 0.895, 0.05]} scale={[0.007, 0.008, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface1964_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.064, -0.004, 0.009]} rotation={[-0.054, -0.283, 0.106]} scale={[0.014, 0.012, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2549_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.133, -0.019, -0.222]} rotation={[-0.341, 0.981, 0.074]} scale={0.012} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2892_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.197, 0.017, -0.232]} rotation={[-0.069, 0.895, 0.05]} scale={[0.007, 0.008, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube204_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.055, 0.08, -0.139]} rotation={[0.03, 1.379, -0.76]} scale={[0.011, 0.002, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube207_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.069, 0.062, -0.166]} rotation={[-2.989, 0.389, 2.98]} scale={0.005} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2220_lambert7_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.108, -0.132]} rotation={[-0.095, -0.011, 0.038]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2220_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.108, -0.132]} rotation={[-0.095, -0.011, 0.038]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2220_lambert16_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.108, -0.132]} rotation={[-0.095, -0.011, 0.038]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2220_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.108, -0.132]} rotation={[-0.095, -0.011, 0.038]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2221_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.108, -0.132]} rotation={[-0.095, -0.011, 0.038]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2222_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.108, -0.132]} rotation={[-0.095, -0.011, 0.038]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2218_lambert16_0.geometry} material={materials.PaletteMaterial001} position={[0.003, 0, -0.002]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2407_lambert16_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2407_lambert20_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2407_lambert4_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2407_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2407_lambert6_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2407_lambert7_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2486_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2486_lambert7_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert7_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert4_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert12_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert13_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_blinn2_0.geometry} material={materials.PaletteMaterial003} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert6_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert16_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_blinn7_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert20_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert8_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert11_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert15_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert9_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert17_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2534_lambert14_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2547_blinn1_0.geometry} material={materials.PaletteMaterial004} position={[-0.008, -0.032, 0.045]} rotation={[0, 0.047, 0]} scale={0.013} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2547_blinn7_0.geometry} material={materials.PaletteMaterial001} position={[-0.008, -0.032, 0.045]} rotation={[0, 0.047, 0]} scale={0.013} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder20_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder20_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder20_lambert18_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder21_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.039, 0.122, -0.145]} rotation={[1.005, 0.175, -0.46]} scale={[0, 0.001, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder21_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.039, 0.122, -0.145]} rotation={[1.005, 0.175, -0.46]} scale={[0, 0.001, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube239_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.072, 0.091, -0.199]} rotation={[2.705, -0.275, 1.375]} scale={[0.005, 0.008, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube240_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.109, 0.057, -0.17]} rotation={[-2.708, 0.993, 2.819]} scale={[0.009, 0.011, 0.009]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2548_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.044, 0.119, -0.116]} rotation={[0.016, 0.981, -0.376]} scale={[0.024, 0.017, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube241_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.042, 0.126, -0.114]} rotation={[2.73, -0.62, 2.502]} scale={[0.02, 0.001, 0.014]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube242_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.038, 0.086, 0.032]} rotation={[-0.089, 0.005, 0.066]} scale={[0.007, 0.002, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube243_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.04, 0.083, 0.032]} rotation={[-3.054, 0.545, 3.055]} scale={[0.007, 0.002, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube244_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.039, 0.081, 0.032]} rotation={[-3.054, 0.545, 3.055]} scale={[0.007, 0.001, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube246_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.03, 0.08, 0.011]} rotation={[0.022, -0.378, -0.089]} scale={[0.006, 0.001, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube265_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.107, 0.082, -0.096]} rotation={[0.3, 1.097, -0.294]} scale={[0.006, 0.001, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube247_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.031, 0.078, 0.011]} rotation={[-0.085, 0.025, -0.16]} scale={[0.006, 0.002, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2574_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.034, 0.027, -0.235]} rotation={[0, -1.332, -0.141]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2599_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.012, -0.004, 0.063]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube252_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.054, 0.047, -0.065]} rotation={[3.061, -0.942, 3.042]} scale={0.004} />
      <mesh castShadow receiveShadow geometry={nodes.pCube249_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.049, 0.071, -0.069]} rotation={[-0.068, -1.234, -0.157]} scale={[0.007, 0.002, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube250_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.034, 0.083, 0.015]} rotation={[0.228, -0.64, -0.034]} scale={[0.002, 0.002, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube251_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.034, 0.082, 0.01]} rotation={[-0.112, 0.26, -0.318]} scale={[0.002, 0.002, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube253_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.051, 0.075, 0.053]} rotation={[-0.087, 0.016, -0.058]} scale={[0.041, 0.007, 0.041]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube255_blinn16_0.geometry} material={materials.PaletteMaterial001} position={[-0.01, -0.03, 0.035]} rotation={[0.004, 0, -0.002]} scale={0.012} />
      <mesh castShadow receiveShadow geometry={nodes.pCube256_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.022, 0.132, -0.173]} rotation={[0.069, -0.004, -0.045]} scale={[0.035, 0.009, 0.032]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube258_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.299, -0.04, -0.319]} rotation={[2.765, 0.001, 2.99]} scale={[0.015, 0.015, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube299_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.29, -0.04, -0.313]} rotation={[2.765, 0.001, 2.99]} scale={[0.015, 0.015, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube259_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.206, -0.036, 0.06]} rotation={[2.356, 1.204, -2.645]} scale={[0.015, 0.02, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube260_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.04, 0.129, -0.164]} rotation={[0.259, -0.365, -0.491]} scale={[0.022, 0.005, 0.022]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder22_blinn8_0.geometry} material={materials.PaletteMaterial001} position={[-0.007, 0.106, -0.188]} rotation={[0.048, -0.351, 1.341]} scale={[0.011, 0.008, 0.011]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube261_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.225, 0.107, -0.157]} rotation={[2.064, 0.464, 2.997]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube262_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.136, -0.055, 0.138]} rotation={[1.491, 1.091, -1.762]} scale={[0.015, 0.02, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube263_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.022, -0.259, -0.128]} rotation={[1.577, 0.963, -0.676]} scale={[0.015, 0.02, 0.02]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube264_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.05, 0.067, -0.197]} rotation={[-0.06, 0.284, 0.017]} scale={0.049} />
      <mesh castShadow receiveShadow geometry={nodes.pCube266_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.007, 0.029, -0.015]} rotation={[0, 0.264, 0]} scale={0.006} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder25_blinn9_0.geometry} material={materials.PaletteMaterial001} position={[0.032, 0.058, -0.03]} rotation={[0, -0.088, 0]} scale={0.005} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder25_blinn16_0.geometry} material={materials.PaletteMaterial001} position={[0.032, 0.058, -0.03]} rotation={[0, -0.088, 0]} scale={0.005} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder25_lambert23_0.geometry} material={materials.PaletteMaterial001} position={[0.032, 0.058, -0.03]} rotation={[0, -0.088, 0]} scale={0.005} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder25_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.032, 0.058, -0.03]} rotation={[0, -0.088, 0]} scale={0.005} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder25_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.032, 0.058, -0.03]} rotation={[0, -0.088, 0]} scale={0.005} />
      <mesh castShadow receiveShadow geometry={nodes.pCube270_lambert7_0.geometry} material={materials.PaletteMaterial001} position={[0.082, 0.109, -0.046]} rotation={[0, -0.091, -0.005]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube274_lambert7_0.geometry} material={materials.PaletteMaterial001} position={[0.082, 0.109, -0.047]} rotation={[0, -0.091, -0.005]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube275_lambert7_0.geometry} material={materials.PaletteMaterial001} position={[0.082, 0.109, -0.047]} rotation={[0, -0.091, -0.005]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube273_lambert7_0.geometry} material={materials.PaletteMaterial001} position={[0.083, 0.113, -0.057]} rotation={[0, -0.098, Math.PI]} scale={[0, 0, 0.067]} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere2_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.101, 0.079, -0.142]} rotation={[0, 0, -0.185]} scale={0.013} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere2_blinn8_0.geometry} material={materials.PaletteMaterial001} position={[0.101, 0.079, -0.142]} rotation={[0, 0, -0.185]} scale={0.013} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere2_lambert19_0.geometry} material={materials.PaletteMaterial001} position={[0.101, 0.079, -0.142]} rotation={[0, 0, -0.185]} scale={0.013} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere2_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.101, 0.079, -0.142]} rotation={[0, 0, -0.185]} scale={0.013} />
      <mesh castShadow receiveShadow geometry={nodes.pCube276_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.105, 0.09, -0.136]} rotation={[0.442, 0.038, -0.329]} scale={[0.007, 0.002, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube277_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.102, 0.09, -0.144]} rotation={[-0.861, 1.427, 0.74]} scale={[0.011, 0.007, 0.011]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube278_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.213, 0.001, -0.291]} rotation={[2.804, -0.446, 2.705]} scale={[0.008, 0.013, 0.013]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder27_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.003, 0.091, 0.024]} rotation={[-0.426, 0.081, -0.177]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder28_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.015, 0.159, -0.01]} rotation={[-0.426, 0.081, -0.783]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder29_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.048, 0.029, -0.029]} rotation={[0.274, -0.154, -0.499]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pSphere3_blinn8_0.geometry} material={materials.PaletteMaterial001} position={[0.102, 0.081, -0.139]} rotation={[0.076, 0.395, -0.21]} scale={[0.012, 0.002, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2594_blinn8_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.005, 0.002]} rotation={[-0.021, 0.002, -0.006]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2594_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.005, 0.002]} rotation={[-0.021, 0.002, -0.006]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2594_blinn17_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.005, 0.002]} rotation={[-0.021, 0.002, -0.006]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2594_blinn16_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.005, 0.002]} rotation={[-0.021, 0.002, -0.006]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder31_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.036, 0.118, -0.145]} rotation={[-2.304, 0, 0.316]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder31_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.036, 0.118, -0.145]} rotation={[-2.304, 0, 0.316]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder31_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.036, 0.118, -0.145]} rotation={[-2.304, 0, 0.316]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder32_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.038, 0.119, -0.147]} rotation={[-2.304, 0, 0.316]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder32_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.038, 0.119, -0.147]} rotation={[-2.304, 0, 0.316]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder33_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.036, 0.117, -0.147]} rotation={[-2.417, -0.037, 0.314]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder33_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.036, 0.117, -0.147]} rotation={[-2.417, -0.037, 0.314]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder34_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.037, 0.119, -0.146]} rotation={[-2.217, 0.028, 0.315]} scale={[0.001, 0.003, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder34_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.037, 0.119, -0.146]} rotation={[-2.217, 0.028, 0.315]} scale={[0.001, 0.003, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder34_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.037, 0.119, -0.146]} rotation={[-2.217, 0.028, 0.315]} scale={[0.001, 0.003, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder35_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.035, 0.119, -0.146]} rotation={[-2.383, -0.022, 0.354]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder35_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.035, 0.119, -0.146]} rotation={[-2.383, -0.022, 0.354]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder37_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.039, 0.118, -0.147]} rotation={[-2.304, 0, 0.316]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube283_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.038, 0.124, -0.137]} rotation={[-0.088, 0.004, 0.027]} scale={[0.003, 0.003, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube286_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.035, 0.126, -0.134]} rotation={[-0.355, -0.485, -0.082]} scale={[0.004, 0.003, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube287_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.035, 0.131, -0.113]} rotation={[-2.799, 0.164, 3.018]} scale={[0.003, 0.003, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube288_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.122, 0.12, -0.183]} rotation={[2.95, -0.249, 2.638]} scale={[0.005, 0.005, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube290_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.014, 0.096, -0.185]} rotation={[1.529, -1.128, 1.333]} scale={[0.003, 0.003, 0.004]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2596_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.295, 0.029, -0.153]} rotation={[2.83, 1.095, -2.886]} scale={[0.006, 0.005, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2596_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.295, 0.029, -0.153]} rotation={[2.83, 1.095, -2.886]} scale={[0.006, 0.005, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2596_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.295, 0.029, -0.153]} rotation={[2.83, 1.095, -2.886]} scale={[0.006, 0.005, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2597_lambert27_0.geometry} material={materials.PaletteMaterial001} position={[0.192, 0.019, -0.024]} rotation={[-0.046, -0.432, 0.018]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2597_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.192, 0.019, -0.024]} rotation={[-0.046, -0.432, 0.018]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2597_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.192, 0.019, -0.024]} rotation={[-0.046, -0.432, 0.018]} scale={0.008} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2598_lambert18_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2598_blinn8_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2598_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2598_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube295_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.102, 0.086, -0.149]} rotation={[-0.861, 1.427, 1.344]} scale={[0.008, 0.002, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube296_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.102, 0.086, -0.149]} rotation={[-2.593, 1.381, 3.109]} scale={[0.008, 0.002, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder40_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.111, -0.192]} rotation={[0.127, 0, 1.759]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder42_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.002, 0.101, -0.193]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder42_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[-0.002, 0.101, -0.193]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder43_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.008, 0.109, -0.189]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder44_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, 0.105, -0.19]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder67_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.006, 0.105, -0.184]} rotation={[0.136, -0.07, 1.351]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder45_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0.108, -0.185]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder45_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0.108, -0.185]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder80_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[-0.012, 0.114, -0.183]} rotation={[-2.352, -1.446, -0.818]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder48_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0.105, -0.187]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder48_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[-0.01, 0.105, -0.187]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder49_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.011, 0.104, -0.184]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder49_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[-0.011, 0.104, -0.184]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder50_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.002, 0.1, -0.183]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder52_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.102, -0.192]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube298_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.022, 0.123, -0.204]} rotation={[2.485, -1.215, -3]} scale={[0.002, 0.002, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube300_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder56_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.001, 0.112, -0.192]} rotation={[0.127, 0, 1.759]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder57_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.053, 0.103, -0.212]} rotation={[-2.794, 0.35, -1.782]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder58_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder58_lambert38_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder59_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.042, 0.009, -0.279]} rotation={[-Math.PI, -0.069, -Math.PI]} scale={[0.01, 0.009, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder60_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.15, 0.005, -0.143]} rotation={[0, 0.497, 0]} scale={[0.01, 0.009, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder59_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.042, 0.009, -0.279]} rotation={[-Math.PI, -0.069, -Math.PI]} scale={[0.01, 0.009, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder60_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.15, 0.005, -0.143]} rotation={[0, 0.497, 0]} scale={[0.01, 0.009, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder61_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.037, 0.089, -0.209]} rotation={[3.054, 0.066, -1.982]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder62_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.089, -0.207]} rotation={[-3.077, -0.237, -1.697]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder66_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.009, 0.106, -0.184]} rotation={[0.24, 0.379, 1.334]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder63_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.027, 0.075, -0.265]} rotation={[-2.678, 1.1, -2.62]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder64_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.036, 0.091, -0.21]} rotation={[2.999, 0.094, -1.944]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder65_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.043, 0.088, -0.206]} rotation={[2.837, -0.238, -1.909]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder68_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.183, 0.109, -0.009]} rotation={[-0.241, 1.026, 2.114]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder69_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.002, 0.102, -0.193]} rotation={[0.06, -0.389, 1.333]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder70_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.058, 0.085, -0.167]} rotation={[1.099, -0.618, -3.131]} scale={[0.001, 0.003, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder71_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.058, 0.08, -0.1]} rotation={[-2.965, -0.742, -2.134]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder72_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.036, 0.082, -0.159]} rotation={[0.073, -0.367, 0.836]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder73_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.075, 0.08, -0.164]} rotation={[0.203, 0.723, 0.909]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder73_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.075, 0.08, -0.164]} rotation={[0.203, 0.723, 0.909]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube301_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.062, 0.122, -0.198]} scale={0.011} />
      <mesh castShadow receiveShadow geometry={nodes.pCube302_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.017, 0.123, -0.202]} rotation={[0.952, 1.071, -1.142]} scale={[0.002, 0.001, 0.004]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder74_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.021, 0.128, -0.169]} rotation={[0.775, 0.495, -0.024]} scale={[0.001, 0.01, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder74_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.021, 0.128, -0.169]} rotation={[0.775, 0.495, -0.024]} scale={[0.001, 0.01, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder74_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.021, 0.128, -0.169]} rotation={[0.775, 0.495, -0.024]} scale={[0.001, 0.01, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder75_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.028, 0.125, -0.167]} rotation={[0.122, 0.239, -0.291]} scale={[0.002, 0.01, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder75_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.028, 0.125, -0.167]} rotation={[0.122, 0.239, -0.291]} scale={[0.002, 0.01, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder76_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.021, 0.136, -0.161]} rotation={[0.418, 0.181, -0.532]} scale={[0.002, 0.004, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder76_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.021, 0.136, -0.161]} rotation={[0.418, 0.181, -0.532]} scale={[0.002, 0.004, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder77_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.033, 0.136, -0.165]} rotation={[0.79, 0.389, -0.874]} scale={[0.002, 0.004, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder77_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.033, 0.136, -0.165]} rotation={[0.79, 0.389, -0.874]} scale={[0.002, 0.004, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder78_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[-0.02, 0.113, -0.196]} rotation={[-0.045, -0.459, 1.297]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder79_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[-0.027, 0.12, -0.186]} rotation={[0.101, 0.053, 1.415]} scale={0.002} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder83_lambert18_0.geometry} material={materials.PaletteMaterial001} position={[0.078, 0.108, -0.162]} rotation={[-0.28, -0.223, 0.342]} scale={[0.002, 0.003, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2769_blinn8_0.geometry} material={materials.PaletteMaterial001} position={[0.001, 0.016, -0.027]} rotation={[0.001, 0, -0.001]} scale={0.009} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2769_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.001, 0.016, -0.027]} rotation={[0.001, 0, -0.001]} scale={0.009} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder80_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[-0.012, 0.114, -0.183]} rotation={[-2.352, -1.446, -0.818]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder81_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.012, 0.114, -0.184]} rotation={[-2.352, -1.446, -0.818]} scale={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder84_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.045, 0.115, -0.126]} rotation={[-0.581, -0.536, 1.038]} scale={[0.003, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2812_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[-0.019, 0.355, -0.114]} rotation={[-1.791, 0.266, -0.874]} scale={[0.012, 0.009, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2812_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.019, 0.355, -0.114]} rotation={[-1.791, 0.266, -0.874]} scale={[0.012, 0.009, 0.012]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2809_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[0.418, -0.004, -0.289]} rotation={[-2.943, 1.055, 2.858]} scale={[0.011, 0.013, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2809_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.418, -0.004, -0.289]} rotation={[-2.943, 1.055, 2.858]} scale={[0.011, 0.013, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2809_lambert13_0.geometry} material={materials.PaletteMaterial001} position={[0.418, -0.004, -0.289]} rotation={[-2.943, 1.055, 2.858]} scale={[0.011, 0.013, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2811_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0, -0.001, 0]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2901_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[-0.007, 0.024, -0.363]} rotation={[3.1, 0.922, -2.81]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2901_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.007, 0.024, -0.363]} rotation={[3.1, 0.922, -2.81]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2904_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[-0.007, 0.024, -0.363]} rotation={[3.1, 0.922, -2.81]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2904_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.007, 0.024, -0.363]} rotation={[3.1, 0.922, -2.81]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2891_lambert26_0.geometry} material={materials.PaletteMaterial001} position={[0.058, 0.038, -0.279]} rotation={[-2.805, -1.239, -2.94]} scale={[0.008, 0.006, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2891_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.058, 0.038, -0.279]} rotation={[-2.805, -1.239, -2.94]} scale={[0.008, 0.006, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2572_lambert2_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube343_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.131, 0.074, -0.225]} rotation={[-0.089, 0.005, 0.066]} scale={[0.052, 0.018, 0.052]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2898_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.355, -0.055, -0.031]} rotation={[-1.631, 1.206, 2.065]} scale={[0.01, 0.011, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2900_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[0.106, -0.013, -0.068]} rotation={[0.061, 0.51, -0.048]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2900_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.106, -0.013, -0.068]} rotation={[0.061, 0.51, -0.048]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2899_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.087, -0.061, -0.001]} rotation={[0.079, -0.285, -0.24]} scale={[0.01, 0.012, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2899_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[-0.087, -0.061, -0.001]} rotation={[0.079, -0.285, -0.24]} scale={[0.01, 0.012, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder85_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[-0.111, 0.071, -0.169]} rotation={[-0.041, -0.181, -0.107]} scale={[0.003, 0.01, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube345_lambert28_0.geometry} material={materials.PaletteMaterial001} position={[-0.125, 0.001, -0.185]} rotation={[-0.037, 0.204, 0.256]} scale={[0.008, 0.008, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube346_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.1, 0.086, -0.175]} rotation={[2.887, 0.643, -2.856]} scale={[0.004, 0.003, 0.005]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder86_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.028, 0.125, -0.167]} rotation={[0.122, 0.239, -0.291]} scale={[0.002, 0.01, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2903_lambert12_0.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2905_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[-0.142, 0.086, -0.274]} rotation={[-3.131, 0.083, -2.648]} scale={0.006} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2905_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.142, 0.086, -0.274]} rotation={[-3.131, 0.083, -2.648]} scale={0.006} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2906_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[0.407, 0.006, -0.144]} rotation={[0, 0.921, 0.12]} scale={[0.01, 0.012, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface2906_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.407, 0.006, -0.144]} rotation={[0, 0.921, 0.12]} scale={[0.01, 0.012, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube347_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.09, 0.13, -0.202]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube348_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.08, 0.122, -0.157]} rotation={[-0.487, -0.477, 1.491]} scale={[0.001, 0.001, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube349_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.122, 0.079, -0.213]} rotation={[2.494, -0.162, -2.161]} scale={[0.007, 0.004, 0.004]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube350_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.064, 0.102, -0.22]} scale={[0.01, 0.01, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube351_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.05, 0.132, -0.21]} rotation={[-1.593, -0.13, 0.953]} scale={[0.006, 0.002, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube352_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[-0.058, 0.124, -0.226]} rotation={[0.015, -0.47, 0.087]} scale={[0.01, 0.01, 0.007]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube353_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.188, 0.137, -0.209]} rotation={[-2.283, 0.078, 0.669]} scale={[0.007, 0.003, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube354_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.201, 0.132, -0.203]} rotation={[0.071, 0.475, 1.323]} scale={[0.004, 0.003, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube355_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.175, 0.11, -0.197]} rotation={[0.88, -0.859, 1.453]} scale={[0.003, 0.002, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn3_0.geometry} material={materials.PaletteMaterial005} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_lambert3_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn4_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn1_0.geometry} material={materials.PaletteMaterial004} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_lambert39_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_lambert5_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn5_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn12_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn19_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn14_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn20_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_lambert40_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn2_0.geometry} material={materials.PaletteMaterial003} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn13_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.polySurface3025_blinn15_0.geometry} material={materials.PaletteMaterial001} position={[0.002, 0, 0.002]} rotation={[0, 0, 0.021]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.pCube356_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.245, 0.116, -0.086]} rotation={[-0.448, -1.017, 1.542]} scale={[0.008, 0.004, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube357_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.256, 0.106, -0.1]} rotation={[0.245, -0.225, 0.742]} scale={[0.004, 0.003, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder87_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.093, 0.08, -0.15]} rotation={[1.429, 0, 0.282]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder87_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.093, 0.08, -0.15]} rotation={[1.429, 0, 0.282]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder88_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.095, 0.139, -0.142]} rotation={[0.034, 0.509, 1.49]} scale={[0, 0.005, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder88_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.095, 0.139, -0.142]} rotation={[0.034, 0.509, 1.49]} scale={[0, 0.005, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder89_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.101, 0.074, -0.144]} rotation={[2.147, 0.271, -2.997]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder89_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.101, 0.074, -0.144]} rotation={[2.147, 0.271, -2.997]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder89_lambert12_0.geometry} material={materials.PaletteMaterial001} position={[0.101, 0.074, -0.144]} rotation={[2.147, 0.271, -2.997]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder90_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.094, 0.086, -0.154]} rotation={[0.023, 0, -1.643]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder91_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.098, 0.092, -0.15]} rotation={[-0.113, 0.649, -2.139]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube358_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.235, 0.079, -0.088]} rotation={[0.085, -0.019, -0.099]} scale={[0.032, 0.007, 0.032]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube359_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.209, 0.076, -0.045]} rotation={[-0.232, -1.263, -0.334]} scale={[0.042, 0.007, 0.042]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder92_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.102, 0.087, -0.155]} rotation={[0.003, -0.076, -1.532]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder93_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.102, 0.087, -0.155]} rotation={[0.003, -0.076, -1.532]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube360_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.142, 0.079, -0.167]} rotation={[3.054, -0.613, 3.092]} scale={[0.003, 0.001, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder94_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.098, 0.092, -0.15]} rotation={[-0.113, 0.649, -2.139]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube361_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.179, 0.084, 0.015]} scale={0.014} />
      <mesh castShadow receiveShadow geometry={nodes.pCube362_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.183, 0.088, 0.019]} rotation={[1.004, 0.597, -0.745]} scale={[0.008, 0.004, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.pCube363_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.179, 0.091, 0.018]} rotation={[0.251, -0.731, 1.091]} scale={[0.006, 0.006, 0.01]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder95_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.104, 0.085, -0.154]} rotation={[0, 0, -Math.PI / 2]} scale={[0.002, 0.003, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder96_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.185, 0.078, 0.014]} rotation={[1.471, 0.079, 0.52]} scale={[0, 0.003, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder97_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.186, 0.082, 0.005]} rotation={[0.417, 1.288, 1.142]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder98_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.185, 0.082, 0.005]} rotation={[0.417, 1.288, 1.142]} scale={[0, 0.01, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder99_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.095, 0.085, -0.154]} rotation={[-0.012, 0.126, -1.479]} scale={[0.001, 0.01, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder100_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.095, 0.086, -0.154]} rotation={[-0.012, 0.126, -1.479]} scale={[0.001, 0.01, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder101_lambert2_0.geometry} material={materials.PaletteMaterial001} position={[0.095, 0.085, -0.154]} rotation={[-0.012, 0.126, -1.479]} scale={[0.001, 0.01, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.pCylinder115_lambert38_0.geometry} material={materials.PaletteMaterial001} position={[0.071, 0.008, -0.037]} rotation={[0.245, 0.683, -0.074]} scale={0.008} />
      <instancedMesh args={[nodes.polySurface853_lambert28_0.geometry, materials.PaletteMaterial001, 8]} castShadow receiveShadow instanceMatrix={nodes.polySurface853_lambert28_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube133_lambert28_0.geometry, materials.PaletteMaterial001, 8]} castShadow receiveShadow instanceMatrix={nodes.pCube133_lambert28_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1064_lambert28_0.geometry, materials.PaletteMaterial001, 23]} castShadow receiveShadow instanceMatrix={nodes.polySurface1064_lambert28_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1122_lambert5_0.geometry, materials.PaletteMaterial001, 7]} castShadow receiveShadow instanceMatrix={nodes.polySurface1122_lambert5_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1122_lambert38_0.geometry, materials.PaletteMaterial001, 7]} castShadow receiveShadow instanceMatrix={nodes.polySurface1122_lambert38_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1128_lambert5_0.geometry, materials.PaletteMaterial001, 7]} castShadow receiveShadow instanceMatrix={nodes.polySurface1128_lambert5_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1128_lambert38_0.geometry, materials.PaletteMaterial001, 7]} castShadow receiveShadow instanceMatrix={nodes.polySurface1128_lambert38_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube179_lambert28_0.geometry, materials.PaletteMaterial001, 6]} castShadow receiveShadow instanceMatrix={nodes.pCube179_lambert28_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('models/snow/colourd_scene-transformed.glb')
